################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/media/rc/keymaps/built-in.o 

C_SRCS += \
../drivers/media/rc/keymaps/rc-adstech-dvb-t-pci.c \
../drivers/media/rc/keymaps/rc-alink-dtu-m.c \
../drivers/media/rc/keymaps/rc-anysee.c \
../drivers/media/rc/keymaps/rc-apac-viewcomp.c \
../drivers/media/rc/keymaps/rc-asus-pc39.c \
../drivers/media/rc/keymaps/rc-ati-tv-wonder-hd-600.c \
../drivers/media/rc/keymaps/rc-ati-x10.c \
../drivers/media/rc/keymaps/rc-avermedia-a16d.c \
../drivers/media/rc/keymaps/rc-avermedia-cardbus.c \
../drivers/media/rc/keymaps/rc-avermedia-dvbt.c \
../drivers/media/rc/keymaps/rc-avermedia-m135a.c \
../drivers/media/rc/keymaps/rc-avermedia-m733a-rm-k6.c \
../drivers/media/rc/keymaps/rc-avermedia-rm-ks.c \
../drivers/media/rc/keymaps/rc-avermedia.c \
../drivers/media/rc/keymaps/rc-avertv-303.c \
../drivers/media/rc/keymaps/rc-azurewave-ad-tu700.c \
../drivers/media/rc/keymaps/rc-behold-columbus.c \
../drivers/media/rc/keymaps/rc-behold.c \
../drivers/media/rc/keymaps/rc-budget-ci-old.c \
../drivers/media/rc/keymaps/rc-cinergy-1400.c \
../drivers/media/rc/keymaps/rc-cinergy.c \
../drivers/media/rc/keymaps/rc-dib0700-nec.c \
../drivers/media/rc/keymaps/rc-dib0700-rc5.c \
../drivers/media/rc/keymaps/rc-digitalnow-tinytwin.c \
../drivers/media/rc/keymaps/rc-digittrade.c \
../drivers/media/rc/keymaps/rc-dm1105-nec.c \
../drivers/media/rc/keymaps/rc-dntv-live-dvb-t.c \
../drivers/media/rc/keymaps/rc-dntv-live-dvbt-pro.c \
../drivers/media/rc/keymaps/rc-em-terratec.c \
../drivers/media/rc/keymaps/rc-encore-enltv-fm53.c \
../drivers/media/rc/keymaps/rc-encore-enltv.c \
../drivers/media/rc/keymaps/rc-encore-enltv2.c \
../drivers/media/rc/keymaps/rc-evga-indtube.c \
../drivers/media/rc/keymaps/rc-eztv.c \
../drivers/media/rc/keymaps/rc-flydvb.c \
../drivers/media/rc/keymaps/rc-flyvideo.c \
../drivers/media/rc/keymaps/rc-fusionhdtv-mce.c \
../drivers/media/rc/keymaps/rc-gadmei-rm008z.c \
../drivers/media/rc/keymaps/rc-genius-tvgo-a11mce.c \
../drivers/media/rc/keymaps/rc-gotview7135.c \
../drivers/media/rc/keymaps/rc-hauppauge.c \
../drivers/media/rc/keymaps/rc-imon-mce.c \
../drivers/media/rc/keymaps/rc-imon-pad.c \
../drivers/media/rc/keymaps/rc-iodata-bctv7e.c \
../drivers/media/rc/keymaps/rc-it913x-v1.c \
../drivers/media/rc/keymaps/rc-it913x-v2.c \
../drivers/media/rc/keymaps/rc-kaiomy.c \
../drivers/media/rc/keymaps/rc-kworld-315u.c \
../drivers/media/rc/keymaps/rc-kworld-pc150u.c \
../drivers/media/rc/keymaps/rc-kworld-plus-tv-analog.c \
../drivers/media/rc/keymaps/rc-leadtek-y04g0051.c \
../drivers/media/rc/keymaps/rc-lirc.c \
../drivers/media/rc/keymaps/rc-lme2510.c \
../drivers/media/rc/keymaps/rc-manli.c \
../drivers/media/rc/keymaps/rc-medion-x10.c \
../drivers/media/rc/keymaps/rc-msi-digivox-ii.c \
../drivers/media/rc/keymaps/rc-msi-digivox-iii.c \
../drivers/media/rc/keymaps/rc-msi-tvanywhere-plus.c \
../drivers/media/rc/keymaps/rc-msi-tvanywhere.c \
../drivers/media/rc/keymaps/rc-nebula.c \
../drivers/media/rc/keymaps/rc-nec-terratec-cinergy-xs.c \
../drivers/media/rc/keymaps/rc-norwood.c \
../drivers/media/rc/keymaps/rc-npgtech.c \
../drivers/media/rc/keymaps/rc-pctv-sedna.c \
../drivers/media/rc/keymaps/rc-pinnacle-color.c \
../drivers/media/rc/keymaps/rc-pinnacle-grey.c \
../drivers/media/rc/keymaps/rc-pinnacle-pctv-hd.c \
../drivers/media/rc/keymaps/rc-pixelview-002t.c \
../drivers/media/rc/keymaps/rc-pixelview-mk12.c \
../drivers/media/rc/keymaps/rc-pixelview-new.c \
../drivers/media/rc/keymaps/rc-pixelview.c \
../drivers/media/rc/keymaps/rc-powercolor-real-angel.c \
../drivers/media/rc/keymaps/rc-proteus-2309.c \
../drivers/media/rc/keymaps/rc-purpletv.c \
../drivers/media/rc/keymaps/rc-pv951.c \
../drivers/media/rc/keymaps/rc-rc6-mce.c \
../drivers/media/rc/keymaps/rc-real-audio-220-32-keys.c \
../drivers/media/rc/keymaps/rc-snapstream-firefly.c \
../drivers/media/rc/keymaps/rc-streamzap.c \
../drivers/media/rc/keymaps/rc-tbs-nec.c \
../drivers/media/rc/keymaps/rc-technisat-usb2.c \
../drivers/media/rc/keymaps/rc-terratec-cinergy-xs.c \
../drivers/media/rc/keymaps/rc-terratec-slim-2.c \
../drivers/media/rc/keymaps/rc-terratec-slim.c \
../drivers/media/rc/keymaps/rc-tevii-nec.c \
../drivers/media/rc/keymaps/rc-tivo.c \
../drivers/media/rc/keymaps/rc-total-media-in-hand.c \
../drivers/media/rc/keymaps/rc-trekstor.c \
../drivers/media/rc/keymaps/rc-tt-1500.c \
../drivers/media/rc/keymaps/rc-twinhan1027.c \
../drivers/media/rc/keymaps/rc-videomate-m1f.c \
../drivers/media/rc/keymaps/rc-videomate-s350.c \
../drivers/media/rc/keymaps/rc-videomate-tv-pvr.c \
../drivers/media/rc/keymaps/rc-winfast-usbii-deluxe.c \
../drivers/media/rc/keymaps/rc-winfast.c 

OBJS += \
./drivers/media/rc/keymaps/rc-adstech-dvb-t-pci.o \
./drivers/media/rc/keymaps/rc-alink-dtu-m.o \
./drivers/media/rc/keymaps/rc-anysee.o \
./drivers/media/rc/keymaps/rc-apac-viewcomp.o \
./drivers/media/rc/keymaps/rc-asus-pc39.o \
./drivers/media/rc/keymaps/rc-ati-tv-wonder-hd-600.o \
./drivers/media/rc/keymaps/rc-ati-x10.o \
./drivers/media/rc/keymaps/rc-avermedia-a16d.o \
./drivers/media/rc/keymaps/rc-avermedia-cardbus.o \
./drivers/media/rc/keymaps/rc-avermedia-dvbt.o \
./drivers/media/rc/keymaps/rc-avermedia-m135a.o \
./drivers/media/rc/keymaps/rc-avermedia-m733a-rm-k6.o \
./drivers/media/rc/keymaps/rc-avermedia-rm-ks.o \
./drivers/media/rc/keymaps/rc-avermedia.o \
./drivers/media/rc/keymaps/rc-avertv-303.o \
./drivers/media/rc/keymaps/rc-azurewave-ad-tu700.o \
./drivers/media/rc/keymaps/rc-behold-columbus.o \
./drivers/media/rc/keymaps/rc-behold.o \
./drivers/media/rc/keymaps/rc-budget-ci-old.o \
./drivers/media/rc/keymaps/rc-cinergy-1400.o \
./drivers/media/rc/keymaps/rc-cinergy.o \
./drivers/media/rc/keymaps/rc-dib0700-nec.o \
./drivers/media/rc/keymaps/rc-dib0700-rc5.o \
./drivers/media/rc/keymaps/rc-digitalnow-tinytwin.o \
./drivers/media/rc/keymaps/rc-digittrade.o \
./drivers/media/rc/keymaps/rc-dm1105-nec.o \
./drivers/media/rc/keymaps/rc-dntv-live-dvb-t.o \
./drivers/media/rc/keymaps/rc-dntv-live-dvbt-pro.o \
./drivers/media/rc/keymaps/rc-em-terratec.o \
./drivers/media/rc/keymaps/rc-encore-enltv-fm53.o \
./drivers/media/rc/keymaps/rc-encore-enltv.o \
./drivers/media/rc/keymaps/rc-encore-enltv2.o \
./drivers/media/rc/keymaps/rc-evga-indtube.o \
./drivers/media/rc/keymaps/rc-eztv.o \
./drivers/media/rc/keymaps/rc-flydvb.o \
./drivers/media/rc/keymaps/rc-flyvideo.o \
./drivers/media/rc/keymaps/rc-fusionhdtv-mce.o \
./drivers/media/rc/keymaps/rc-gadmei-rm008z.o \
./drivers/media/rc/keymaps/rc-genius-tvgo-a11mce.o \
./drivers/media/rc/keymaps/rc-gotview7135.o \
./drivers/media/rc/keymaps/rc-hauppauge.o \
./drivers/media/rc/keymaps/rc-imon-mce.o \
./drivers/media/rc/keymaps/rc-imon-pad.o \
./drivers/media/rc/keymaps/rc-iodata-bctv7e.o \
./drivers/media/rc/keymaps/rc-it913x-v1.o \
./drivers/media/rc/keymaps/rc-it913x-v2.o \
./drivers/media/rc/keymaps/rc-kaiomy.o \
./drivers/media/rc/keymaps/rc-kworld-315u.o \
./drivers/media/rc/keymaps/rc-kworld-pc150u.o \
./drivers/media/rc/keymaps/rc-kworld-plus-tv-analog.o \
./drivers/media/rc/keymaps/rc-leadtek-y04g0051.o \
./drivers/media/rc/keymaps/rc-lirc.o \
./drivers/media/rc/keymaps/rc-lme2510.o \
./drivers/media/rc/keymaps/rc-manli.o \
./drivers/media/rc/keymaps/rc-medion-x10.o \
./drivers/media/rc/keymaps/rc-msi-digivox-ii.o \
./drivers/media/rc/keymaps/rc-msi-digivox-iii.o \
./drivers/media/rc/keymaps/rc-msi-tvanywhere-plus.o \
./drivers/media/rc/keymaps/rc-msi-tvanywhere.o \
./drivers/media/rc/keymaps/rc-nebula.o \
./drivers/media/rc/keymaps/rc-nec-terratec-cinergy-xs.o \
./drivers/media/rc/keymaps/rc-norwood.o \
./drivers/media/rc/keymaps/rc-npgtech.o \
./drivers/media/rc/keymaps/rc-pctv-sedna.o \
./drivers/media/rc/keymaps/rc-pinnacle-color.o \
./drivers/media/rc/keymaps/rc-pinnacle-grey.o \
./drivers/media/rc/keymaps/rc-pinnacle-pctv-hd.o \
./drivers/media/rc/keymaps/rc-pixelview-002t.o \
./drivers/media/rc/keymaps/rc-pixelview-mk12.o \
./drivers/media/rc/keymaps/rc-pixelview-new.o \
./drivers/media/rc/keymaps/rc-pixelview.o \
./drivers/media/rc/keymaps/rc-powercolor-real-angel.o \
./drivers/media/rc/keymaps/rc-proteus-2309.o \
./drivers/media/rc/keymaps/rc-purpletv.o \
./drivers/media/rc/keymaps/rc-pv951.o \
./drivers/media/rc/keymaps/rc-rc6-mce.o \
./drivers/media/rc/keymaps/rc-real-audio-220-32-keys.o \
./drivers/media/rc/keymaps/rc-snapstream-firefly.o \
./drivers/media/rc/keymaps/rc-streamzap.o \
./drivers/media/rc/keymaps/rc-tbs-nec.o \
./drivers/media/rc/keymaps/rc-technisat-usb2.o \
./drivers/media/rc/keymaps/rc-terratec-cinergy-xs.o \
./drivers/media/rc/keymaps/rc-terratec-slim-2.o \
./drivers/media/rc/keymaps/rc-terratec-slim.o \
./drivers/media/rc/keymaps/rc-tevii-nec.o \
./drivers/media/rc/keymaps/rc-tivo.o \
./drivers/media/rc/keymaps/rc-total-media-in-hand.o \
./drivers/media/rc/keymaps/rc-trekstor.o \
./drivers/media/rc/keymaps/rc-tt-1500.o \
./drivers/media/rc/keymaps/rc-twinhan1027.o \
./drivers/media/rc/keymaps/rc-videomate-m1f.o \
./drivers/media/rc/keymaps/rc-videomate-s350.o \
./drivers/media/rc/keymaps/rc-videomate-tv-pvr.o \
./drivers/media/rc/keymaps/rc-winfast-usbii-deluxe.o \
./drivers/media/rc/keymaps/rc-winfast.o 

C_DEPS += \
./drivers/media/rc/keymaps/rc-adstech-dvb-t-pci.d \
./drivers/media/rc/keymaps/rc-alink-dtu-m.d \
./drivers/media/rc/keymaps/rc-anysee.d \
./drivers/media/rc/keymaps/rc-apac-viewcomp.d \
./drivers/media/rc/keymaps/rc-asus-pc39.d \
./drivers/media/rc/keymaps/rc-ati-tv-wonder-hd-600.d \
./drivers/media/rc/keymaps/rc-ati-x10.d \
./drivers/media/rc/keymaps/rc-avermedia-a16d.d \
./drivers/media/rc/keymaps/rc-avermedia-cardbus.d \
./drivers/media/rc/keymaps/rc-avermedia-dvbt.d \
./drivers/media/rc/keymaps/rc-avermedia-m135a.d \
./drivers/media/rc/keymaps/rc-avermedia-m733a-rm-k6.d \
./drivers/media/rc/keymaps/rc-avermedia-rm-ks.d \
./drivers/media/rc/keymaps/rc-avermedia.d \
./drivers/media/rc/keymaps/rc-avertv-303.d \
./drivers/media/rc/keymaps/rc-azurewave-ad-tu700.d \
./drivers/media/rc/keymaps/rc-behold-columbus.d \
./drivers/media/rc/keymaps/rc-behold.d \
./drivers/media/rc/keymaps/rc-budget-ci-old.d \
./drivers/media/rc/keymaps/rc-cinergy-1400.d \
./drivers/media/rc/keymaps/rc-cinergy.d \
./drivers/media/rc/keymaps/rc-dib0700-nec.d \
./drivers/media/rc/keymaps/rc-dib0700-rc5.d \
./drivers/media/rc/keymaps/rc-digitalnow-tinytwin.d \
./drivers/media/rc/keymaps/rc-digittrade.d \
./drivers/media/rc/keymaps/rc-dm1105-nec.d \
./drivers/media/rc/keymaps/rc-dntv-live-dvb-t.d \
./drivers/media/rc/keymaps/rc-dntv-live-dvbt-pro.d \
./drivers/media/rc/keymaps/rc-em-terratec.d \
./drivers/media/rc/keymaps/rc-encore-enltv-fm53.d \
./drivers/media/rc/keymaps/rc-encore-enltv.d \
./drivers/media/rc/keymaps/rc-encore-enltv2.d \
./drivers/media/rc/keymaps/rc-evga-indtube.d \
./drivers/media/rc/keymaps/rc-eztv.d \
./drivers/media/rc/keymaps/rc-flydvb.d \
./drivers/media/rc/keymaps/rc-flyvideo.d \
./drivers/media/rc/keymaps/rc-fusionhdtv-mce.d \
./drivers/media/rc/keymaps/rc-gadmei-rm008z.d \
./drivers/media/rc/keymaps/rc-genius-tvgo-a11mce.d \
./drivers/media/rc/keymaps/rc-gotview7135.d \
./drivers/media/rc/keymaps/rc-hauppauge.d \
./drivers/media/rc/keymaps/rc-imon-mce.d \
./drivers/media/rc/keymaps/rc-imon-pad.d \
./drivers/media/rc/keymaps/rc-iodata-bctv7e.d \
./drivers/media/rc/keymaps/rc-it913x-v1.d \
./drivers/media/rc/keymaps/rc-it913x-v2.d \
./drivers/media/rc/keymaps/rc-kaiomy.d \
./drivers/media/rc/keymaps/rc-kworld-315u.d \
./drivers/media/rc/keymaps/rc-kworld-pc150u.d \
./drivers/media/rc/keymaps/rc-kworld-plus-tv-analog.d \
./drivers/media/rc/keymaps/rc-leadtek-y04g0051.d \
./drivers/media/rc/keymaps/rc-lirc.d \
./drivers/media/rc/keymaps/rc-lme2510.d \
./drivers/media/rc/keymaps/rc-manli.d \
./drivers/media/rc/keymaps/rc-medion-x10.d \
./drivers/media/rc/keymaps/rc-msi-digivox-ii.d \
./drivers/media/rc/keymaps/rc-msi-digivox-iii.d \
./drivers/media/rc/keymaps/rc-msi-tvanywhere-plus.d \
./drivers/media/rc/keymaps/rc-msi-tvanywhere.d \
./drivers/media/rc/keymaps/rc-nebula.d \
./drivers/media/rc/keymaps/rc-nec-terratec-cinergy-xs.d \
./drivers/media/rc/keymaps/rc-norwood.d \
./drivers/media/rc/keymaps/rc-npgtech.d \
./drivers/media/rc/keymaps/rc-pctv-sedna.d \
./drivers/media/rc/keymaps/rc-pinnacle-color.d \
./drivers/media/rc/keymaps/rc-pinnacle-grey.d \
./drivers/media/rc/keymaps/rc-pinnacle-pctv-hd.d \
./drivers/media/rc/keymaps/rc-pixelview-002t.d \
./drivers/media/rc/keymaps/rc-pixelview-mk12.d \
./drivers/media/rc/keymaps/rc-pixelview-new.d \
./drivers/media/rc/keymaps/rc-pixelview.d \
./drivers/media/rc/keymaps/rc-powercolor-real-angel.d \
./drivers/media/rc/keymaps/rc-proteus-2309.d \
./drivers/media/rc/keymaps/rc-purpletv.d \
./drivers/media/rc/keymaps/rc-pv951.d \
./drivers/media/rc/keymaps/rc-rc6-mce.d \
./drivers/media/rc/keymaps/rc-real-audio-220-32-keys.d \
./drivers/media/rc/keymaps/rc-snapstream-firefly.d \
./drivers/media/rc/keymaps/rc-streamzap.d \
./drivers/media/rc/keymaps/rc-tbs-nec.d \
./drivers/media/rc/keymaps/rc-technisat-usb2.d \
./drivers/media/rc/keymaps/rc-terratec-cinergy-xs.d \
./drivers/media/rc/keymaps/rc-terratec-slim-2.d \
./drivers/media/rc/keymaps/rc-terratec-slim.d \
./drivers/media/rc/keymaps/rc-tevii-nec.d \
./drivers/media/rc/keymaps/rc-tivo.d \
./drivers/media/rc/keymaps/rc-total-media-in-hand.d \
./drivers/media/rc/keymaps/rc-trekstor.d \
./drivers/media/rc/keymaps/rc-tt-1500.d \
./drivers/media/rc/keymaps/rc-twinhan1027.d \
./drivers/media/rc/keymaps/rc-videomate-m1f.d \
./drivers/media/rc/keymaps/rc-videomate-s350.d \
./drivers/media/rc/keymaps/rc-videomate-tv-pvr.d \
./drivers/media/rc/keymaps/rc-winfast-usbii-deluxe.d \
./drivers/media/rc/keymaps/rc-winfast.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/media/rc/keymaps/%.o: ../drivers/media/rc/keymaps/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


