################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ELF_SRCS := 
O_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
SECONDARY_SIZE := 
OBJS := 
C_DEPS := 
ASM_DEPS := 
SECONDARY_FLASH := 
EXECUTABLES := 
SECONDARY_LIST := 
S_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
. \
virt/kvm \
usr \
tools/vm \
tools/virtio \
tools/virtio/vhost_test \
tools/usb \
tools/testing/selftests/vm \
tools/testing/selftests/breakpoints \
tools/power/x86/x86_energy_perf_policy \
tools/power/x86/turbostat \
tools/power/cpupower/utils/idle_monitor \
tools/power/cpupower/utils/helpers \
tools/power/cpupower/utils \
tools/power/cpupower/lib \
tools/power/cpupower/debug/kernel \
tools/power/cpupower/debug/i386 \
tools/power/cpupower/bench \
tools/perf/util \
tools/perf/util/ui \
tools/perf/util/ui/browsers \
tools/perf/util/scripting-engines \
tools/perf/util/gtk \
tools/perf/scripts/python/Perf-Trace-Util \
tools/perf/scripts/perl/Perf-Trace-Util \
tools/perf \
tools/perf/bench \
tools/perf/arch/x86/util \
tools/perf/arch/sparc/util \
tools/perf/arch/sh/util \
tools/perf/arch/s390/util \
tools/perf/arch/powerpc/util \
tools/perf/arch/arm/util \
tools/lguest \
tools/hv \
tools/firewire \
sound/usb/usx2y \
sound/usb \
sound/usb/misc \
sound/usb/caiaq \
sound/usb/6fire \
sound/synth \
sound/synth/emux \
sound/spi \
sound/sparc \
sound \
sound/soc/txx9 \
sound/soc/tegra \
sound/soc \
sound/soc/sh \
sound/soc/samsung \
sound/soc/samsung/srp_alp \
sound/soc/s6000 \
sound/soc/pxa \
sound/soc/omap \
sound/soc/nuc900 \
sound/soc/nexell \
sound/soc/mxs \
sound/soc/mid-x86 \
sound/soc/kirkwood \
sound/soc/jz4740 \
sound/soc/imx \
sound/soc/fsl \
sound/soc/ep93xx \
sound/soc/davinci \
sound/soc/codecs \
sound/soc/blackfin \
sound/soc/au1x \
sound/soc/atmel \
sound/sh \
sound/ppc \
sound/pcmcia/vx \
sound/pcmcia/pdaudiocf \
sound/pci/ymfpci \
sound/pci/vx222 \
sound/pci \
sound/pci/trident \
sound/pci/rme9652 \
sound/pci/riptide \
sound/pci/pcxhr \
sound/pci/oxygen \
sound/pci/nm256 \
sound/pci/mixart \
sound/pci/lx6464es \
sound/pci/lola \
sound/pci/korg1212 \
sound/pci/ice1712 \
sound/pci/hda \
sound/pci/emu10k1 \
sound/pci/echoaudio \
sound/pci/ctxfi \
sound/pci/cs5535audio \
sound/pci/cs46xx \
sound/pci/ca0106 \
sound/pci/aw2 \
sound/pci/au88x0 \
sound/pci/asihpi \
sound/pci/ali5451 \
sound/pci/ac97 \
sound/parisc \
sound/oss \
sound/oss/dmasound \
sound/mips \
sound/isa/wss \
sound/isa/wavefront \
sound/isa \
sound/isa/sb \
sound/isa/opti9xx \
sound/isa/msnd \
sound/isa/gus \
sound/isa/galaxy \
sound/isa/es1688 \
sound/isa/cs423x \
sound/isa/ad1848 \
sound/isa/ad1816a \
sound/i2c \
sound/i2c/other \
sound/firewire \
sound/drivers/vx \
sound/drivers \
sound/drivers/pcsp \
sound/drivers/opl4 \
sound/drivers/opl3 \
sound/drivers/mpu401 \
sound/core \
sound/core/seq \
sound/core/seq/oss \
sound/core/oss \
sound/atmel \
sound/arm \
sound/aoa/soundbus \
sound/aoa/soundbus/i2sbus \
sound/aoa/fabrics \
sound/aoa/core \
sound/aoa/codecs \
security/yama \
security/tomoyo \
security/smack \
security/selinux \
security/selinux/ss \
security \
security/keys \
security/keys/encrypted-keys \
security/integrity/ima \
security/integrity \
security/integrity/evm \
security/apparmor \
scripts \
scripts/selinux/mdp \
scripts/selinux/genheaders \
scripts/mod \
scripts/kconfig \
scripts/kconfig/lxdialog \
scripts/genksyms \
scripts/dtc \
scripts/dtc/libfdt \
scripts/basic \
samples/uhid \
samples/tracepoints \
samples/trace_events \
samples/rpmsg \
samples/kprobes \
samples/kobject \
samples/kfifo \
samples/kdb \
samples/hw_breakpoint \
samples/hidraw \
net/xfrm \
net/x25 \
net/wireless \
net/wimax \
net/wanrouter \
net/unix \
net/tipc \
net \
net/sunrpc \
net/sunrpc/xprtrdma \
net/sunrpc/auth_gss \
net/sctp \
net/sched \
net/rxrpc \
net/rose \
net/rfkill \
net/rds \
net/phonet \
net/packet \
net/openvswitch \
net/nfc \
net/nfc/nci \
net/nfc/llcp \
net/netrom \
net/netlink \
net/netlabel \
net/netfilter \
net/netfilter/ipvs \
net/netfilter/ipset \
net/mac80211 \
net/llc \
net/lapb \
net/l2tp \
net/key \
net/iucv \
net/irda \
net/irda/irnet \
net/irda/irlan \
net/irda/ircomm \
net/ipx \
net/ipv6 \
net/ipv6/netfilter \
net/ipv4 \
net/ipv4/netfilter \
net/ieee802154 \
net/ethernet \
net/econet \
net/dsa \
net/dns_resolver \
net/decnet \
net/decnet/netfilter \
net/dccp \
net/dccp/ccids/lib \
net/dccp/ccids \
net/dcb \
net/core \
net/ceph \
net/ceph/crush \
net/can \
net/caif \
net/bridge/netfilter \
net/bridge \
net/bluetooth \
net/bluetooth/rfcomm \
net/bluetooth/hidp \
net/bluetooth/cmtp \
net/bluetooth/bnep \
net/batman-adv \
net/ax25 \
net/atm \
net/appletalk \
net/9p \
net/8021q \
net/802 \
mm \
lib/zlib_inflate \
lib/zlib_deflate \
lib/xz \
lib \
lib/reed_solomon \
lib/raid6/test \
lib/raid6 \
lib/mpi \
lib/lzo \
kernel \
kernel/trace \
kernel/time \
kernel/sched \
kernel/power \
kernel/irq \
kernel/gcov \
kernel/events \
kernel/debug/kdb \
kernel/debug \
ipc \
init \
include/asm-generic \
fs/yaffs2 \
fs/xfs \
fs \
fs/ufs \
fs/udf \
fs/ubifs \
fs/sysv \
fs/sysfs \
fs/squashfs \
fs/romfs \
fs/reiserfs \
fs/ramfs \
fs/quota \
fs/qnx6 \
fs/qnx4 \
fs/pstore \
fs/proc \
fs/openpromfs \
fs/omfs \
fs/ocfs2 \
fs/ocfs2/dlmfs \
fs/ocfs2/dlm \
fs/ocfs2/cluster \
fs/ntfs \
fs/notify \
fs/notify/inotify \
fs/notify/fanotify \
fs/notify/dnotify \
fs/nls \
fs/nilfs2 \
fs/nfsd \
fs/nfs_common \
fs/nfs \
fs/nfs/objlayout \
fs/nfs/blocklayout \
fs/ncpfs \
fs/minix \
fs/logfs \
fs/lockd \
fs/jfs \
fs/jffs2 \
fs/jbd2 \
fs/jbd \
fs/isofs \
fs/hugetlbfs \
fs/hppfs \
fs/hpfs \
fs/hostfs \
fs/hfsplus \
fs/hfs \
fs/gfs2 \
fs/fuse \
fs/fscache \
fs/freevxfs \
fs/fat \
fs/ext4 \
fs/ext3 \
fs/ext2 \
fs/exportfs \
fs/exofs \
fs/efs \
fs/ecryptfs \
fs/dlm \
fs/devpts \
fs/debugfs \
fs/cramfs \
fs/configfs \
fs/coda \
fs/cifs \
fs/ceph \
fs/cachefiles \
fs/btrfs \
fs/bfs \
fs/befs \
fs/autofs4 \
fs/afs \
fs/affs \
fs/adfs \
fs/9p \
firmware/keyspan_pda \
firmware \
firmware/dsp56k \
firmware/av7110 \
drivers/zorro \
drivers/xen/xenfs \
drivers/xen \
drivers/xen/xenbus \
drivers/xen/xen-pciback \
drivers/watchdog \
drivers/w1 \
drivers/w1/slaves \
drivers/w1/masters \
drivers/vlynq \
drivers/virtio \
drivers/virt \
drivers/video \
drivers/video/via \
drivers/video/vermilion \
drivers/video/sis \
drivers/video/savage \
drivers/video/riva \
drivers/video/pnx4008 \
drivers/video/omap2 \
drivers/video/omap2/omapfb \
drivers/video/omap2/dss \
drivers/video/omap2/displays \
drivers/video/omap \
drivers/video/nvidia \
drivers/video/msm \
drivers/video/mbx \
drivers/video/mb862xx \
drivers/video/matrox \
drivers/video/logo \
drivers/video/kyro \
drivers/video/intelfb \
drivers/video/i810 \
drivers/video/geode \
drivers/video/exynos \
drivers/video/console \
drivers/video/backlight \
drivers/video/aty \
drivers/vhost \
drivers/uwb \
drivers/uwb/i1480 \
drivers/uwb/i1480/dfu \
drivers/usb/wusbcore \
drivers/usb \
drivers/usb/storage \
drivers/usb/serial \
drivers/usb/renesas_usbhs \
drivers/usb/otg \
drivers/usb/musb \
drivers/usb/mon \
drivers/usb/misc \
drivers/usb/misc/sisusbvga \
drivers/usb/image \
drivers/usb/host \
drivers/usb/host/whci \
drivers/usb/host/dwc_otg \
drivers/usb/host/dwc_common_port \
drivers/usb/gadget \
drivers/usb/early \
drivers/usb/dwc3 \
drivers/usb/core \
drivers/usb/class \
drivers/usb/c67x00 \
drivers/usb/atm \
drivers/uio \
drivers/tty/vt \
drivers/tty \
drivers/tty/serial \
drivers/tty/serial/jsm \
drivers/tty/serial/cpm_uart \
drivers/tty/serial/8250 \
drivers/tty/ipwireless \
drivers/tty/hvc \
drivers/thermal \
drivers/tc \
drivers/target/tcm_fc \
drivers/target \
drivers/target/loopback \
drivers/target/iscsi \
drivers/switch \
drivers/staging/zsmalloc \
drivers/staging/zram \
drivers/staging/zcache \
drivers/staging/xgifb \
drivers/staging/wlan-ng \
drivers/staging/wlags49_h25 \
drivers/staging/wlags49_h2 \
drivers/staging/winbond \
drivers/staging/vt6656 \
drivers/staging/vt6655 \
drivers/staging/vme \
drivers/staging/vme/devices \
drivers/staging/vme/bridges \
drivers/staging/vme/boards \
drivers/staging/usbip \
drivers/staging/usbip/userspace/src \
drivers/staging/usbip/userspace/libsrc \
drivers/staging/tidspbridge/rmgr \
drivers/staging/tidspbridge/pmgr \
drivers/staging/tidspbridge/hw \
drivers/staging/tidspbridge/gen \
drivers/staging/tidspbridge/dynload \
drivers/staging/tidspbridge/core \
drivers/staging/telephony \
drivers/staging/ste_rmi4 \
drivers/staging \
drivers/staging/speakup \
drivers/staging/sm7xx \
drivers/staging/slicoss \
drivers/staging/serqt_usb2 \
drivers/staging/serial \
drivers/staging/sep \
drivers/staging/sbe-2t3e3 \
drivers/staging/rts_pstor \
drivers/staging/rts5139 \
drivers/staging/rtl8712 \
drivers/staging/rtl8192u \
drivers/staging/rtl8192u/ieee80211 \
drivers/staging/rtl8192e \
drivers/staging/rtl8192e/rtl8192e \
drivers/staging/rtl8187se \
drivers/staging/rtl8187se/ieee80211 \
drivers/staging/ramster \
drivers/staging/ramster/cluster \
drivers/staging/quickstart \
drivers/staging/quatech_usb2 \
drivers/staging/phison \
drivers/staging/panel \
drivers/staging/ozwpan \
drivers/staging/omapdrm \
drivers/staging/olpc_dcon \
drivers/staging/octeon \
drivers/staging/nvec \
drivers/staging/mei \
drivers/staging/media/solo6x10 \
drivers/staging/media/lirc \
drivers/staging/media/go7007 \
drivers/staging/media/easycap \
drivers/staging/media/dt3155v4l \
drivers/staging/media/cxd2099 \
drivers/staging/media/as102 \
drivers/staging/line6 \
drivers/staging/keucr \
drivers/staging/iio/trigger \
drivers/staging/iio \
drivers/staging/iio/resolver \
drivers/staging/iio/pressure \
drivers/staging/iio/meter \
drivers/staging/iio/magnetometer \
drivers/staging/iio/light \
drivers/staging/iio/imu/mpu/inv_test \
drivers/staging/iio/imu/mpu \
drivers/staging/iio/imu \
drivers/staging/iio/impedance-analyzer \
drivers/staging/iio/gyro \
drivers/staging/iio/dds \
drivers/staging/iio/dac \
drivers/staging/iio/cdc \
drivers/staging/iio/addac \
drivers/staging/iio/adc \
drivers/staging/iio/accel \
drivers/staging/iio/Documentation \
drivers/staging/ft1000/ft1000-usb \
drivers/staging/ft1000/ft1000-pcmcia \
drivers/staging/frontier \
drivers/staging/et131x \
drivers/staging/echo \
drivers/staging/cxt1e1 \
drivers/staging/crystalhd \
drivers/staging/cptm1217 \
drivers/staging/comedi \
drivers/staging/comedi/kcomedilib \
drivers/staging/comedi/drivers \
drivers/staging/comedi/drivers/addi-data \
drivers/staging/bcm \
drivers/staging/asus_oled \
drivers/staging/android \
drivers/staging/android/switch \
drivers/ssb \
drivers/spi \
drivers/sn \
drivers/sh/superhyway \
drivers/sh \
drivers/sh/maple \
drivers/sh/intc \
drivers/sh/clk \
drivers/sfi \
drivers/scsi \
drivers/scsi/ufs \
drivers/scsi/sym53c8xx_2 \
drivers/scsi/qla4xxx \
drivers/scsi/qla2xxx \
drivers/scsi/pm8001 \
drivers/scsi/pcmcia \
drivers/scsi/osd \
drivers/scsi/mvsas \
drivers/scsi/mpt2sas \
drivers/scsi/megaraid \
drivers/scsi/lpfc \
drivers/scsi/libsas \
drivers/scsi/libfc \
drivers/scsi/isci \
drivers/scsi/ibmvscsi \
drivers/scsi/fnic \
drivers/scsi/fcoe \
drivers/scsi/device_handler \
drivers/scsi/cxgbi \
drivers/scsi/cxgbi/cxgb4i \
drivers/scsi/cxgbi/cxgb3i \
drivers/scsi/bnx2i \
drivers/scsi/bnx2fc \
drivers/scsi/bfa \
drivers/scsi/be2iscsi \
drivers/scsi/arm \
drivers/scsi/arcmsr \
drivers/scsi/aic94xx \
drivers/scsi/aic7xxx_old \
drivers/scsi/aic7xxx \
drivers/scsi/aic7xxx/aicasm \
drivers/scsi/aacraid \
drivers/sbus/char \
drivers/s390/scsi \
drivers/s390/net \
drivers/s390/kvm \
drivers/s390/crypto \
drivers/s390/cio \
drivers/s390/char \
drivers/s390/block \
drivers/rtc \
drivers/rpmsg \
drivers/remoteproc \
drivers/regulator \
drivers/rapidio/switches \
drivers/rapidio \
drivers/rapidio/devices \
drivers/ptp \
drivers/ps3 \
drivers/pps \
drivers/pps/generators \
drivers/pps/clients \
drivers/power \
drivers/pnp \
drivers/pnp/pnpbios \
drivers/pnp/pnpacpi \
drivers/pnp/isapnp \
drivers/platform/x86 \
drivers/platform \
drivers/pinctrl \
drivers/pcmcia \
drivers/pci \
drivers/pci/pcie \
drivers/pci/pcie/aer \
drivers/pci/hotplug \
drivers/parport \
drivers/parisc \
drivers/oprofile \
drivers/of \
drivers/nubus \
drivers/nfc \
drivers/net \
drivers/net/xen-netback \
drivers/net/wireless/zd1211rw \
drivers/net/wireless \
drivers/net/wireless/wl12xx \
drivers/net/wireless/wl1251 \
drivers/net/wireless/rtlwifi \
drivers/net/wireless/rtlwifi/rtl8192se \
drivers/net/wireless/rtlwifi/rtl8192de \
drivers/net/wireless/rtlwifi/rtl8192cu \
drivers/net/wireless/rtlwifi/rtl8192ce \
drivers/net/wireless/rtlwifi/rtl8192c \
drivers/net/wireless/rtl818x/rtl8187 \
drivers/net/wireless/rtl818x/rtl8180 \
drivers/net/wireless/rt2x00 \
drivers/net/wireless/prism54 \
drivers/net/wireless/p54 \
drivers/net/wireless/orinoco \
drivers/net/wireless/mwifiex \
drivers/net/wireless/libertas_tf \
drivers/net/wireless/libertas \
drivers/net/wireless/iwmc3200wifi \
drivers/net/wireless/iwlwifi \
drivers/net/wireless/iwlegacy \
drivers/net/wireless/ipw2x00 \
drivers/net/wireless/hostap \
drivers/net/wireless/brcm80211/brcmutil \
drivers/net/wireless/brcm80211/brcmsmac \
drivers/net/wireless/brcm80211/brcmsmac/phy \
drivers/net/wireless/brcm80211/brcmfmac \
drivers/net/wireless/bcmdhd \
drivers/net/wireless/b43legacy \
drivers/net/wireless/b43 \
drivers/net/wireless/ath \
drivers/net/wireless/ath/carl9170 \
drivers/net/wireless/ath/ath9k \
drivers/net/wireless/ath/ath6kl \
drivers/net/wireless/ath/ath5k \
drivers/net/wimax/i2400m \
drivers/net/wan \
drivers/net/wan/lmc \
drivers/net/vmxnet3 \
drivers/net/usb \
drivers/net/tokenring \
drivers/net/team \
drivers/net/slip \
drivers/net/ppp \
drivers/net/plip \
drivers/net/phy \
drivers/net/irda \
drivers/net/hyperv \
drivers/net/hippi \
drivers/net/hamradio \
drivers/net/fddi/skfp \
drivers/net/fddi \
drivers/net/ethernet/xscale \
drivers/net/ethernet/xscale/ixp2000 \
drivers/net/ethernet/xircom \
drivers/net/ethernet/xilinx \
drivers/net/ethernet/via \
drivers/net/ethernet/tundra \
drivers/net/ethernet/toshiba \
drivers/net/ethernet/tile \
drivers/net/ethernet/ti \
drivers/net/ethernet/tehuti \
drivers/net/ethernet/sun \
drivers/net/ethernet/stmicro/stmmac \
drivers/net/ethernet/smsc \
drivers/net/ethernet/sis \
drivers/net/ethernet/silan \
drivers/net/ethernet/sgi \
drivers/net/ethernet/sfc \
drivers/net/ethernet/seeq \
drivers/net/ethernet \
drivers/net/ethernet/renesas \
drivers/net/ethernet/realtek \
drivers/net/ethernet/rdc \
drivers/net/ethernet/racal \
drivers/net/ethernet/qlogic/qlge \
drivers/net/ethernet/qlogic/qlcnic \
drivers/net/ethernet/qlogic \
drivers/net/ethernet/qlogic/netxen \
drivers/net/ethernet/pasemi \
drivers/net/ethernet/packetengines \
drivers/net/ethernet/oki-semi/pch_gbe \
drivers/net/ethernet/octeon \
drivers/net/ethernet/nxp \
drivers/net/ethernet/nvidia \
drivers/net/ethernet/nuvoton \
drivers/net/ethernet/neterion/vxge \
drivers/net/ethernet/neterion \
drivers/net/ethernet/natsemi \
drivers/net/ethernet/myricom/myri10ge \
drivers/net/ethernet/microchip \
drivers/net/ethernet/micrel \
drivers/net/ethernet/mellanox/mlx4 \
drivers/net/ethernet/marvell \
drivers/net/ethernet/intel/ixgbevf \
drivers/net/ethernet/intel/ixgbe \
drivers/net/ethernet/intel/ixgb \
drivers/net/ethernet/intel/igbvf \
drivers/net/ethernet/intel/igb \
drivers/net/ethernet/intel/e1000e \
drivers/net/ethernet/intel/e1000 \
drivers/net/ethernet/intel \
drivers/net/ethernet/icplus \
drivers/net/ethernet/ibm \
drivers/net/ethernet/ibm/emac \
drivers/net/ethernet/ibm/ehea \
drivers/net/ethernet/i825xx \
drivers/net/ethernet/hp \
drivers/net/ethernet/fujitsu \
drivers/net/ethernet/freescale \
drivers/net/ethernet/freescale/fs_enet \
drivers/net/ethernet/faraday \
drivers/net/ethernet/emulex/benet \
drivers/net/ethernet/dlink \
drivers/net/ethernet/dec/tulip \
drivers/net/ethernet/dec \
drivers/net/ethernet/davicom \
drivers/net/ethernet/cisco/enic \
drivers/net/ethernet/cirrus \
drivers/net/ethernet/chelsio/cxgb4vf \
drivers/net/ethernet/chelsio/cxgb4 \
drivers/net/ethernet/chelsio/cxgb3 \
drivers/net/ethernet/chelsio/cxgb \
drivers/net/ethernet/calxeda \
drivers/net/ethernet/cadence \
drivers/net/ethernet/brocade/bna \
drivers/net/ethernet/broadcom \
drivers/net/ethernet/broadcom/bnx2x \
drivers/net/ethernet/atheros/atlx \
drivers/net/ethernet/atheros/atl1e \
drivers/net/ethernet/atheros/atl1c \
drivers/net/ethernet/apple \
drivers/net/ethernet/amd \
drivers/net/ethernet/alteon \
drivers/net/ethernet/aeroflex \
drivers/net/ethernet/adi \
drivers/net/ethernet/adaptec \
drivers/net/ethernet/8390 \
drivers/net/ethernet/3com \
drivers/net/dsa \
drivers/net/cris \
drivers/net/can \
drivers/net/can/usb/peak_usb \
drivers/net/can/usb \
drivers/net/can/softing \
drivers/net/can/sja1000 \
drivers/net/can/mscan \
drivers/net/can/cc770 \
drivers/net/can/c_can \
drivers/net/caif \
drivers/net/bonding \
drivers/net/arcnet \
drivers/net/appletalk \
drivers/mtd/ubi \
drivers/mtd/tests \
drivers/mtd \
drivers/mtd/onenand \
drivers/mtd/nand \
drivers/mtd/nand/gpmi-nand \
drivers/mtd/maps \
drivers/mtd/lpddr \
drivers/mtd/devices \
drivers/mtd/chips \
drivers/mmc/host \
drivers/mmc/core \
drivers/mmc/card \
drivers/mmc \
drivers/misc \
drivers/misc/ti-st \
drivers/misc/sgi-xp \
drivers/misc/sgi-gru \
drivers/misc/lis3lv02d \
drivers/misc/iwmc3200top \
drivers/misc/ibmasm \
drivers/misc/eeprom \
drivers/misc/cb710 \
drivers/misc/carma \
drivers/misc/c2port \
drivers/misc/altera-stapl \
drivers/mfd \
drivers/message/i2o \
drivers/message/fusion \
drivers/memstick/host \
drivers/memstick/core \
drivers/media/video \
drivers/media/video/zoran \
drivers/media/video/uvc \
drivers/media/video/usbvision \
drivers/media/video/tm6000 \
drivers/media/video/tlg2300 \
drivers/media/video/sn9c102 \
drivers/media/video/saa7164 \
drivers/media/video/saa7134 \
drivers/media/video/s5p-tv \
drivers/media/video/s5p-mfc \
drivers/media/video/s5p-jpeg \
drivers/media/video/s5p-g2d \
drivers/media/video/s5p-fimc \
drivers/media/video/pwc \
drivers/media/video/pvrusb2 \
drivers/media/video/omap3isp \
drivers/media/video/omap \
drivers/media/video/nexell/out \
drivers/media/video/nexell/out/hdmi-emul \
drivers/media/video/nexell/out/hdmi \
drivers/media/video/nexell \
drivers/media/video/nexell/m2m \
drivers/media/video/nexell/capture \
drivers/media/video/marvell-ccic \
drivers/media/video/m5mols \
drivers/media/video/ivtv \
drivers/media/video/hdpvr \
drivers/media/video/gspca \
drivers/media/video/gspca/stv06xx \
drivers/media/video/gspca/m5602 \
drivers/media/video/gspca/gl860 \
drivers/media/video/exynos/tv \
drivers/media/video/exynos/rotator \
drivers/media/video/exynos/mipi-csis \
drivers/media/video/exynos/mfc \
drivers/media/video/exynos/mdev \
drivers/media/video/exynos/jpeg \
drivers/media/video/exynos/gsc \
drivers/media/video/exynos/fimg2d \
drivers/media/video/exynos/fimc-lite \
drivers/media/video/exynos/fimc-is-mc2 \
drivers/media/video/exynos/fimc-is-mc \
drivers/media/video/et61x251 \
drivers/media/video/em28xx \
drivers/media/video/davinci \
drivers/media/video/cx88 \
drivers/media/video/cx25840 \
drivers/media/video/cx25821 \
drivers/media/video/cx23885 \
drivers/media/video/cx231xx \
drivers/media/video/cx18 \
drivers/media/video/cpia2 \
drivers/media/video/bt8xx \
drivers/media/video/blackfin \
drivers/media/video/au0828 \
drivers/media/rc \
drivers/media/rc/keymaps \
drivers/media/radio/wl128x \
drivers/media/radio \
drivers/media/radio/si470x \
drivers/media \
drivers/media/dvb/ttusb-dec \
drivers/media/dvb/ttusb-budget \
drivers/media/dvb/ttpci \
drivers/media/dvb/siano \
drivers/media/dvb/pt1 \
drivers/media/dvb/pluto2 \
drivers/media/dvb/ngene \
drivers/media/dvb/mantis \
drivers/media/dvb/frontends \
drivers/media/dvb/firewire \
drivers/media/dvb/dvb-usb \
drivers/media/dvb/dvb-core \
drivers/media/dvb/dm1105 \
drivers/media/dvb/ddbridge \
drivers/media/dvb/bt8xx \
drivers/media/dvb/b2c2 \
drivers/media/common/tuners \
drivers/media/common \
drivers/md \
drivers/md/persistent-data \
drivers/mca \
drivers/macintosh \
drivers/macintosh/ams \
drivers/lguest/x86 \
drivers/lguest \
drivers/leds \
drivers/isdn/sc \
drivers/isdn/pcbit \
drivers/isdn/mISDN \
drivers/isdn/isdnloop \
drivers/isdn/icn \
drivers/isdn/i4l \
drivers/isdn/hysdn \
drivers/isdn/hisax \
drivers/isdn/hardware/mISDN \
drivers/isdn/hardware/eicon \
drivers/isdn/hardware/avm \
drivers/isdn/gigaset \
drivers/isdn/divert \
drivers/isdn/capi \
drivers/isdn/act2000 \
drivers/iommu \
drivers/input/touchscreen \
drivers/input/tablet \
drivers/input \
drivers/input/serio \
drivers/input/mouse \
drivers/input/misc \
drivers/input/keyboard \
drivers/input/joystick \
drivers/input/joystick/iforce \
drivers/input/gameport \
drivers/infiniband/ulp/srpt \
drivers/infiniband/ulp/srp \
drivers/infiniband/ulp/iser \
drivers/infiniband/ulp/ipoib \
drivers/infiniband/hw/qib \
drivers/infiniband/hw/nes \
drivers/infiniband/hw/mthca \
drivers/infiniband/hw/mlx4 \
drivers/infiniband/hw/ipath \
drivers/infiniband/hw/ehca \
drivers/infiniband/hw/cxgb4 \
drivers/infiniband/hw/cxgb3 \
drivers/infiniband/hw/amso1100 \
drivers/infiniband/core \
drivers/ieee802154 \
drivers/idle \
drivers/ide \
drivers/i2c/muxes \
drivers/i2c \
drivers/i2c/busses \
drivers/i2c/algos \
drivers/hwspinlock \
drivers/hwmon \
drivers/hwmon/pmbus \
drivers/hv \
drivers/hsi \
drivers/hsi/clients \
drivers/hid/usbhid \
drivers/hid \
drivers/gud/MobiCoreKernelApi \
drivers/gud/MobiCoreDriver \
drivers/gpu/vga \
drivers/gpu/stub \
drivers/gpu/ion/tegra \
drivers/gpu/ion/nexell \
drivers/gpu/ion \
drivers/gpu/ion/exynos \
drivers/gpu/drm/vmwgfx \
drivers/gpu/drm/via \
drivers/gpu/drm/udl \
drivers/gpu/drm/ttm \
drivers/gpu/drm/tdfx \
drivers/gpu/drm/sis \
drivers/gpu/drm/savage \
drivers/gpu/drm/radeon \
drivers/gpu/drm/r128 \
drivers/gpu/drm/nouveau \
drivers/gpu/drm/mga \
drivers/gpu/drm/i915 \
drivers/gpu/drm/i810 \
drivers/gpu/drm/i2c \
drivers/gpu/drm/gma500 \
drivers/gpu/drm/exynos \
drivers/gpu/drm \
drivers/gpu \
drivers/gpu/arm/t6xx/kbase/src/platform \
drivers/gpu/arm/t6xx/kbase/src/linux \
drivers/gpu/arm/t6xx/kbase/src/linux/config/tpip \
drivers/gpu/arm/t6xx/kbase/src/linux/config \
drivers/gpu/arm/t6xx/kbase/src/common \
drivers/gpu/arm/t6xx/kbase/osk/src/linux \
drivers/gpu/arm/t6xx/kbase/osk/src/common \
drivers/gpu/arm \
drivers/gpio \
drivers/firmware \
drivers/firmware/google \
drivers/firewire \
drivers/eisa \
drivers/edac \
drivers/dma \
drivers/dma/ppc4xx \
drivers/dma/ipu \
drivers/dma/ioat \
drivers/dio \
drivers/devfreq \
drivers/dca \
drivers/crypto \
drivers/crypto/caam \
drivers/crypto/amcc \
drivers/cpuidle \
drivers/cpuidle/governors \
drivers/cpufreq \
drivers/connector \
drivers/clocksource \
drivers/clk \
drivers/char/xilinx_hwicap \
drivers/char \
drivers/char/tpm \
drivers/char/pcmcia \
drivers/char/mwave \
drivers/char/ipmi \
drivers/char/hw_random \
drivers/char/agp \
drivers/cdrom \
drivers \
drivers/bluetooth \
drivers/block \
drivers/block/xen-blkback \
drivers/block/paride \
drivers/block/mtip32xx \
drivers/block/drbd \
drivers/block/aoe \
drivers/bcma \
drivers/base \
drivers/base/regmap \
drivers/base/power \
drivers/auxdisplay \
drivers/atm \
drivers/ata \
drivers/amba \
drivers/acpi \
drivers/acpi/apei \
drivers/acpi/acpica \
drivers/accessibility/braille \
crypto \
crypto/async_tx \
block \
block/partitions \
Documentation/watchdog/src \
Documentation/vDSO \
Documentation/timers \
Documentation/spi \
Documentation/ptp \
Documentation/prctl \
Documentation/pcmcia \
Documentation/networking/timestamping \
Documentation/networking \
Documentation/laptops \
Documentation/ia64 \
Documentation/filesystems \
Documentation/filesystems/configfs \
Documentation/connector \
Documentation/cgroups \
Documentation/blackfin \
Documentation/auxdisplay \
Documentation/arm/SH-Mobile \
Documentation/accounting \
Documentation/EDID \

