#ifndef __CFG_GPIO_VTK_H__
#define __CFG_GPIO_VTK_H__

#include <mach/nxp4330.h>

/*------------------------------------------------------------------------------
 *
 * VTK GPIO settings
 *
 *	(GROUP_A)
 *
 *    0 bit                            4 bit                           8 bit         12 bit   		        16 bit
 *    | GPIO'A'OUTENB and GPIO'A'ALTFN | GPIO'A'OUT or GPIO'A'DETMODE0 | GPIO'A'PUENB| CLKPWR.PADSTRENGTHGPIO'A'|
 *
 -----------------------------------------------------------------------------*/
#define PAD_GPIOA00_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD0 		    ]
#define PAD_GPIOA01_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD1 		    ]
#define PAD_GPIOA02_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD2 		    ]
#define PAD_GPIOA03_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD3 		    ]
#define PAD_GPIOA04_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD4 		    ]
#define PAD_GPIOA05_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD5 		    ]
#define PAD_GPIOA06_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD6 		    ]
#define PAD_GPIOA07_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD7 		    ]

#define PAD_GPIOA08_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: UART0_TX	    ]
#define PAD_GPIOA09_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]
#define PAD_GPIOA10_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]
#define PAD_GPIOA11_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOA12_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]
#define PAD_GPIOA13_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]
#define PAD_GPIOA14_VTK (PAD_MODE_OUT  | PAD_LEVEL_HIGH | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOA15_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: UART1_TX          ]

#define PAD_GPIOA16_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: UART1_RX          ]
#define PAD_GPIOA17_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOA18_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON  | PAD_STRENGTH_2)	// [IN:   CIP_L             ]
#define PAD_GPIOA19_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOA20_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOA21_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: I2S_DOUT          ]
#define PAD_GPIOA22_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: I2S_BCLK          ]
#define PAD_GPIOA23_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: I2S_DIN           ]

#define PAD_GPIOA24_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: I2S_LRCK          ]
#define PAD_GPIOA25_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: I2S_MCLK          ]
#define PAD_GPIOA26_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SCL0              ]
#define PAD_GPIOA27_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SDA0              ]
#define PAD_GPIOA28_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SCL1              ]
#define PAD_GPIOA29_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SDA1              ]
#define PAD_GPIOA30_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PWMOUT0           ]
#define PAD_GPIOA31_VTK (PAD_MODE_OUT  | PAD_LEVEL_HIGH | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:  PWMOUT1           ]

/*------------------------------------------------------------------------------
 *	(GROUP_B)
 *
 *	0 bit				 4 bit				 8 bit	       12 bit			  16 bit
 *	| GPIO'B'OUTENB and GPIO'B'ALTFN | GPIO'B'OUT or GPIO'B'DETMODE0 | GPIO'B'PUENB| CLKPWR.PADSTRENGTHGPIO'B'|
 *
 -----------------------------------------------------------------------------*/
#define PAD_GPIOB00_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_CLK 	]
#define PAD_GPIOB01_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_CMD 	]
#define PAD_GPIOB02_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_DAT0	]
#define PAD_GPIOB03_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_DAT1	]
#define PAD_GPIOB04_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_DAT2	]
#define PAD_GPIOB05_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD0_DAT3	]
#define PAD_GPIOB06_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_CLK 	]
#define PAD_GPIOB07_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_CMD 	]

#define PAD_GPIOB08_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_DAT0	]
#define PAD_GPIOB09_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_DAT1	]
#define PAD_GPIOB10_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_DAT2	]
#define PAD_GPIOB11_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD1_DAT3	]
#define PAD_GPIOB12_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI0_FRM	]
#define PAD_GPIOB13_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI0_CLK	]
#define PAD_GPIOB14_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI0_RXD	]
#define PAD_GPIOB15_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI0_TXD	]

#define PAD_GPIOB16_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD8    	]
#define PAD_GPIOB17_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD9    	]
#define PAD_GPIOB18_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD10   	]
#define PAD_GPIOB19_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD11   	]
#define PAD_GPIOB20_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD12   	]
#define PAD_GPIOB21_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD13   	]
#define PAD_GPIOB22_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD14   	]
#define PAD_GPIOB23_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD15   	]

#define PAD_GPIOB24_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD16   	]
#define PAD_GPIOB25_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD17   	]
#define PAD_GPIOB26_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD18   	]
#define PAD_GPIOB27_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD19   	]
#define PAD_GPIOB28_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD20   	]
#define PAD_GPIOB29_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD21   	]
#define PAD_GPIOB30_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD22   	]
#define PAD_GPIOB31_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVD23   	]

/*------------------------------------------------------------------------------
 *	(GROUP_C)
 *
 *	0 bit				 4 bit				 8 bit	       12 bit			  16 bit
 *	| GPIO'C'OUTENB and GPIO'C'ALTFN | GPIO'C'OUT or GPIO'C'DETMODE0 | GPIO'C'PUENB| CLKPWR.PADSTRENGTHGPIO'C'|
 *
 -----------------------------------------------------------------------------*/

#define PAD_GPIOC00_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VCLK              ]
#define PAD_GPIOC01_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D7            ]
#define PAD_GPIOC02_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:                    ]
#define PAD_GPIOC03_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI1_FRM          ]
#define PAD_GPIOC04_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI1_CLK          ]
#define PAD_GPIOC05_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI1_RXD          ]
#define PAD_GPIOC06_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SPI1_TXD          ]
#define PAD_GPIOC07_VTK (PAD_MODE_OUT  | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [OUT:  USBPWREN          ]

#define PAD_GPIOC08_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D0            ]
#define PAD_GPIOC09_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D1            ]
#define PAD_GPIOC10_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D2            ]
#define PAD_GPIOC11_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D3            ]
#define PAD_GPIOC12_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D4            ]
#define PAD_GPIOC13_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_3)	// [ALT2: VIP_D5            ]
#define PAD_GPIOC14_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VIP_D6            ]
#define PAD_GPIOC15_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]

#define PAD_GPIOC16_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:                     ]
#define PAD_GPIOC17_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: nSCS4             ]
#define PAD_GPIOC18_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: nSCS5             ]
#define PAD_GPIOC19_VTK (PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [IN:   N/C               ]
#define PAD_GPIOC20_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: nNCS1             ]
#define PAD_GPIOC21_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VVSYNC_B          ]
#define PAD_GPIOC22_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VCLK_B            ]
#define PAD_GPIOC23_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VDVALID           ]

#define PAD_GPIOC24_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VHSYNC_B          ]
#define PAD_GPIOC25_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B0            ]
#define PAD_GPIOC26_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B1            ]
#define PAD_GPIOC27_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B2            ]
#define PAD_GPIOC28_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B3            ]
#define PAD_GPIOC29_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B4            ]
#define PAD_GPIOC30_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B5            ]
#define PAD_GPIOC31_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B6            ]

/*------------------------------------------------------------------------------
 *	(GROUP_D)
 *
 *	0 bit                            4 bit                           8 bit         12 bit                     16 bit
 *	| GPIO'C'OUTENB and GPIO'C'ALTFN | GPIO'C'OUT or GPIO'C'DETMODE0 | GPIO'C'PUENB| CLKPWR.PADSTRENGTHGPIO'C'|
 *
 -----------------------------------------------------------------------------*/
#define PAD_GPIOD00_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VID_B7            ]
#define PAD_GPIOD01_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD8               ]
#define PAD_GPIOD02_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD9               ]
#define PAD_GPIOD03_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD10              ]
#define PAD_GPIOD04_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD11              ]
#define PAD_GPIOD05_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD12              ]
#define PAD_GPIOD06_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD13              ]
#define PAD_GPIOD07_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD14              ]

#define PAD_GPIOD08_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SD15              ]
#define PAD_GPIOD09_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA8               ]
#define PAD_GPIOD10_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA9               ]
#define PAD_GPIOD11_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA10              ]
#define PAD_GPIOD12_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA11              ]
#define PAD_GPIOD13_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA12              ]
#define PAD_GPIOD14_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA13              ]
#define PAD_GPIOD15_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA14              ]

#define PAD_GPIOD16_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA15              ]
#define PAD_GPIOD17_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA16              ]
#define PAD_GPIOD18_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA17              ]
#define PAD_GPIOD19_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: SA18              ]
#define PAD_GPIOD20_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVCLK             ]
#define PAD_GPIOD21_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PDE               ]
#define PAD_GPIOD22_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PHSYNC            ]
#define PAD_GPIOD23_VTK (PAD_FUNC_ALT1 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT1: PVSYNC            ]

#define PAD_GPIOD24_VTK (PAD_FUNC_ALT2 | PAD_LEVEL_LOW  | PAD_PULLUP_OFF | PAD_STRENGTH_2)	// [ALT2: VCLK27            ]

/*------------------------------------------------------------------------------
 *	(GROUPALV)
 *	0		      4				    8	     12
 *	| MODE(IN/OUT/DETECT) | ALIVE OUT or ALIVE DETMODE0 | PullUp |
 *
 -----------------------------------------------------------------------------*/
#define	PAD_GPIOALV0_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]
#define	PAD_GPIOALV1_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]
#define	PAD_GPIOALV2_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]
#define	PAD_GPIOALV3_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]
#define	PAD_GPIOALV4_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]
#define	PAD_GPIOALV5_VTK  	(PAD_MODE_IN   | PAD_LEVEL_LOW  | PAD_PULLUP_ON)		// [IN: N/C ]

/*------------------------------------------------------------------------------
 *	(BUS signal)		               [BIT]: 0		8	   12
 *					      	      | BUS Pad | Strength |
 *
 -----------------------------------------------------------------------------*/
#define	PAD_BUS_STATIC_CNTL_VTK	(NX_CLKPWR_BUSPAD_STATIC_CNTL	| PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_VTK	(NX_CLKPWR_BUSPAD_STATIC_ADDR	| PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_VTK	(NX_CLKPWR_BUSPAD_STATIC_DATA	| PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_VTK	(NX_CLKPWR_BUSPAD_HSYNC		| PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_VTK	(NX_CLKPWR_BUSPAD_VSYNC		| PAD_STRENGTH_2)
#define	PAD_BUS_DE_VTK		(NX_CLKPWR_BUSPAD_DE		| PAD_STRENGTH_2)

/*------------------------------------------------------------------------------
 *	GPIO LCD
 */
// defined for VTK board
#define	CFG_PIO_LCD_PCI_ENB			(PAD_GPIO_A + 31)

extern const U32 io_pad_vtk[NUMBER_OF_GPIO_MODULE][32];

#ifndef ALVPADS
#define ALVPADS 6
#endif
extern const U32 alv_pad_vtk[ALVPADS];

extern const U32 bus_pad_vtk[6];

#endif /* __CFG_GPIO_VTK_H__ */
