################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/usb/host/alchemy-common.c \
../drivers/usb/host/ehci-atmel.c \
../drivers/usb/host/ehci-au1xxx.c \
../drivers/usb/host/ehci-cns3xxx.c \
../drivers/usb/host/ehci-dbg.c \
../drivers/usb/host/ehci-fsl.c \
../drivers/usb/host/ehci-grlib.c \
../drivers/usb/host/ehci-hcd.c \
../drivers/usb/host/ehci-hub.c \
../drivers/usb/host/ehci-ixp4xx.c \
../drivers/usb/host/ehci-lpm.c \
../drivers/usb/host/ehci-ls1x.c \
../drivers/usb/host/ehci-mem.c \
../drivers/usb/host/ehci-msm.c \
../drivers/usb/host/ehci-mv.c \
../drivers/usb/host/ehci-mxc.c \
../drivers/usb/host/ehci-octeon.c \
../drivers/usb/host/ehci-omap.c \
../drivers/usb/host/ehci-orion.c \
../drivers/usb/host/ehci-pci.c \
../drivers/usb/host/ehci-platform.c \
../drivers/usb/host/ehci-pmcmsp.c \
../drivers/usb/host/ehci-ppc-of.c \
../drivers/usb/host/ehci-ps3.c \
../drivers/usb/host/ehci-q.c \
../drivers/usb/host/ehci-s5p.c \
../drivers/usb/host/ehci-sched.c \
../drivers/usb/host/ehci-sh.c \
../drivers/usb/host/ehci-spear.c \
../drivers/usb/host/ehci-sysfs.c \
../drivers/usb/host/ehci-tegra.c \
../drivers/usb/host/ehci-vt8500.c \
../drivers/usb/host/ehci-w90x900.c \
../drivers/usb/host/ehci-xilinx-of.c \
../drivers/usb/host/ehci-xls.c \
../drivers/usb/host/fhci-dbg.c \
../drivers/usb/host/fhci-hcd.c \
../drivers/usb/host/fhci-hub.c \
../drivers/usb/host/fhci-mem.c \
../drivers/usb/host/fhci-q.c \
../drivers/usb/host/fhci-sched.c \
../drivers/usb/host/fhci-tds.c \
../drivers/usb/host/fsl-mph-dr-of.c \
../drivers/usb/host/hwa-hc.c \
../drivers/usb/host/imx21-dbg.c \
../drivers/usb/host/imx21-hcd.c \
../drivers/usb/host/isp116x-hcd.c \
../drivers/usb/host/isp1362-hcd.c \
../drivers/usb/host/isp1760-hcd.c \
../drivers/usb/host/isp1760-if.c \
../drivers/usb/host/octeon2-common.c \
../drivers/usb/host/ohci-at91.c \
../drivers/usb/host/ohci-au1xxx.c \
../drivers/usb/host/ohci-cns3xxx.c \
../drivers/usb/host/ohci-da8xx.c \
../drivers/usb/host/ohci-dbg.c \
../drivers/usb/host/ohci-ep93xx.c \
../drivers/usb/host/ohci-exynos.c \
../drivers/usb/host/ohci-hcd.c \
../drivers/usb/host/ohci-hub.c \
../drivers/usb/host/ohci-jz4740.c \
../drivers/usb/host/ohci-mem.c \
../drivers/usb/host/ohci-nxp.c \
../drivers/usb/host/ohci-octeon.c \
../drivers/usb/host/ohci-omap.c \
../drivers/usb/host/ohci-omap3.c \
../drivers/usb/host/ohci-pci.c \
../drivers/usb/host/ohci-platform.c \
../drivers/usb/host/ohci-pnx8550.c \
../drivers/usb/host/ohci-ppc-of.c \
../drivers/usb/host/ohci-ppc-soc.c \
../drivers/usb/host/ohci-ps3.c \
../drivers/usb/host/ohci-pxa27x.c \
../drivers/usb/host/ohci-q.c \
../drivers/usb/host/ohci-s3c2410.c \
../drivers/usb/host/ohci-sa1111.c \
../drivers/usb/host/ohci-sh.c \
../drivers/usb/host/ohci-sm501.c \
../drivers/usb/host/ohci-spear.c \
../drivers/usb/host/ohci-ssb.c \
../drivers/usb/host/ohci-tmio.c \
../drivers/usb/host/ohci-xls.c \
../drivers/usb/host/oxu210hp-hcd.c \
../drivers/usb/host/pci-quirks.c \
../drivers/usb/host/r8a66597-hcd.c \
../drivers/usb/host/sl811-hcd.c \
../drivers/usb/host/sl811_cs.c \
../drivers/usb/host/u132-hcd.c \
../drivers/usb/host/uhci-debug.c \
../drivers/usb/host/uhci-grlib.c \
../drivers/usb/host/uhci-hcd.c \
../drivers/usb/host/uhci-hub.c \
../drivers/usb/host/uhci-pci.c \
../drivers/usb/host/uhci-q.c \
../drivers/usb/host/xhci-dbg.c \
../drivers/usb/host/xhci-hub.c \
../drivers/usb/host/xhci-mem.c \
../drivers/usb/host/xhci-pci.c \
../drivers/usb/host/xhci-plat.c \
../drivers/usb/host/xhci-ring.c \
../drivers/usb/host/xhci.c 

OBJS += \
./drivers/usb/host/alchemy-common.o \
./drivers/usb/host/ehci-atmel.o \
./drivers/usb/host/ehci-au1xxx.o \
./drivers/usb/host/ehci-cns3xxx.o \
./drivers/usb/host/ehci-dbg.o \
./drivers/usb/host/ehci-fsl.o \
./drivers/usb/host/ehci-grlib.o \
./drivers/usb/host/ehci-hcd.o \
./drivers/usb/host/ehci-hub.o \
./drivers/usb/host/ehci-ixp4xx.o \
./drivers/usb/host/ehci-lpm.o \
./drivers/usb/host/ehci-ls1x.o \
./drivers/usb/host/ehci-mem.o \
./drivers/usb/host/ehci-msm.o \
./drivers/usb/host/ehci-mv.o \
./drivers/usb/host/ehci-mxc.o \
./drivers/usb/host/ehci-octeon.o \
./drivers/usb/host/ehci-omap.o \
./drivers/usb/host/ehci-orion.o \
./drivers/usb/host/ehci-pci.o \
./drivers/usb/host/ehci-platform.o \
./drivers/usb/host/ehci-pmcmsp.o \
./drivers/usb/host/ehci-ppc-of.o \
./drivers/usb/host/ehci-ps3.o \
./drivers/usb/host/ehci-q.o \
./drivers/usb/host/ehci-s5p.o \
./drivers/usb/host/ehci-sched.o \
./drivers/usb/host/ehci-sh.o \
./drivers/usb/host/ehci-spear.o \
./drivers/usb/host/ehci-sysfs.o \
./drivers/usb/host/ehci-tegra.o \
./drivers/usb/host/ehci-vt8500.o \
./drivers/usb/host/ehci-w90x900.o \
./drivers/usb/host/ehci-xilinx-of.o \
./drivers/usb/host/ehci-xls.o \
./drivers/usb/host/fhci-dbg.o \
./drivers/usb/host/fhci-hcd.o \
./drivers/usb/host/fhci-hub.o \
./drivers/usb/host/fhci-mem.o \
./drivers/usb/host/fhci-q.o \
./drivers/usb/host/fhci-sched.o \
./drivers/usb/host/fhci-tds.o \
./drivers/usb/host/fsl-mph-dr-of.o \
./drivers/usb/host/hwa-hc.o \
./drivers/usb/host/imx21-dbg.o \
./drivers/usb/host/imx21-hcd.o \
./drivers/usb/host/isp116x-hcd.o \
./drivers/usb/host/isp1362-hcd.o \
./drivers/usb/host/isp1760-hcd.o \
./drivers/usb/host/isp1760-if.o \
./drivers/usb/host/octeon2-common.o \
./drivers/usb/host/ohci-at91.o \
./drivers/usb/host/ohci-au1xxx.o \
./drivers/usb/host/ohci-cns3xxx.o \
./drivers/usb/host/ohci-da8xx.o \
./drivers/usb/host/ohci-dbg.o \
./drivers/usb/host/ohci-ep93xx.o \
./drivers/usb/host/ohci-exynos.o \
./drivers/usb/host/ohci-hcd.o \
./drivers/usb/host/ohci-hub.o \
./drivers/usb/host/ohci-jz4740.o \
./drivers/usb/host/ohci-mem.o \
./drivers/usb/host/ohci-nxp.o \
./drivers/usb/host/ohci-octeon.o \
./drivers/usb/host/ohci-omap.o \
./drivers/usb/host/ohci-omap3.o \
./drivers/usb/host/ohci-pci.o \
./drivers/usb/host/ohci-platform.o \
./drivers/usb/host/ohci-pnx8550.o \
./drivers/usb/host/ohci-ppc-of.o \
./drivers/usb/host/ohci-ppc-soc.o \
./drivers/usb/host/ohci-ps3.o \
./drivers/usb/host/ohci-pxa27x.o \
./drivers/usb/host/ohci-q.o \
./drivers/usb/host/ohci-s3c2410.o \
./drivers/usb/host/ohci-sa1111.o \
./drivers/usb/host/ohci-sh.o \
./drivers/usb/host/ohci-sm501.o \
./drivers/usb/host/ohci-spear.o \
./drivers/usb/host/ohci-ssb.o \
./drivers/usb/host/ohci-tmio.o \
./drivers/usb/host/ohci-xls.o \
./drivers/usb/host/oxu210hp-hcd.o \
./drivers/usb/host/pci-quirks.o \
./drivers/usb/host/r8a66597-hcd.o \
./drivers/usb/host/sl811-hcd.o \
./drivers/usb/host/sl811_cs.o \
./drivers/usb/host/u132-hcd.o \
./drivers/usb/host/uhci-debug.o \
./drivers/usb/host/uhci-grlib.o \
./drivers/usb/host/uhci-hcd.o \
./drivers/usb/host/uhci-hub.o \
./drivers/usb/host/uhci-pci.o \
./drivers/usb/host/uhci-q.o \
./drivers/usb/host/xhci-dbg.o \
./drivers/usb/host/xhci-hub.o \
./drivers/usb/host/xhci-mem.o \
./drivers/usb/host/xhci-pci.o \
./drivers/usb/host/xhci-plat.o \
./drivers/usb/host/xhci-ring.o \
./drivers/usb/host/xhci.o 

C_DEPS += \
./drivers/usb/host/alchemy-common.d \
./drivers/usb/host/ehci-atmel.d \
./drivers/usb/host/ehci-au1xxx.d \
./drivers/usb/host/ehci-cns3xxx.d \
./drivers/usb/host/ehci-dbg.d \
./drivers/usb/host/ehci-fsl.d \
./drivers/usb/host/ehci-grlib.d \
./drivers/usb/host/ehci-hcd.d \
./drivers/usb/host/ehci-hub.d \
./drivers/usb/host/ehci-ixp4xx.d \
./drivers/usb/host/ehci-lpm.d \
./drivers/usb/host/ehci-ls1x.d \
./drivers/usb/host/ehci-mem.d \
./drivers/usb/host/ehci-msm.d \
./drivers/usb/host/ehci-mv.d \
./drivers/usb/host/ehci-mxc.d \
./drivers/usb/host/ehci-octeon.d \
./drivers/usb/host/ehci-omap.d \
./drivers/usb/host/ehci-orion.d \
./drivers/usb/host/ehci-pci.d \
./drivers/usb/host/ehci-platform.d \
./drivers/usb/host/ehci-pmcmsp.d \
./drivers/usb/host/ehci-ppc-of.d \
./drivers/usb/host/ehci-ps3.d \
./drivers/usb/host/ehci-q.d \
./drivers/usb/host/ehci-s5p.d \
./drivers/usb/host/ehci-sched.d \
./drivers/usb/host/ehci-sh.d \
./drivers/usb/host/ehci-spear.d \
./drivers/usb/host/ehci-sysfs.d \
./drivers/usb/host/ehci-tegra.d \
./drivers/usb/host/ehci-vt8500.d \
./drivers/usb/host/ehci-w90x900.d \
./drivers/usb/host/ehci-xilinx-of.d \
./drivers/usb/host/ehci-xls.d \
./drivers/usb/host/fhci-dbg.d \
./drivers/usb/host/fhci-hcd.d \
./drivers/usb/host/fhci-hub.d \
./drivers/usb/host/fhci-mem.d \
./drivers/usb/host/fhci-q.d \
./drivers/usb/host/fhci-sched.d \
./drivers/usb/host/fhci-tds.d \
./drivers/usb/host/fsl-mph-dr-of.d \
./drivers/usb/host/hwa-hc.d \
./drivers/usb/host/imx21-dbg.d \
./drivers/usb/host/imx21-hcd.d \
./drivers/usb/host/isp116x-hcd.d \
./drivers/usb/host/isp1362-hcd.d \
./drivers/usb/host/isp1760-hcd.d \
./drivers/usb/host/isp1760-if.d \
./drivers/usb/host/octeon2-common.d \
./drivers/usb/host/ohci-at91.d \
./drivers/usb/host/ohci-au1xxx.d \
./drivers/usb/host/ohci-cns3xxx.d \
./drivers/usb/host/ohci-da8xx.d \
./drivers/usb/host/ohci-dbg.d \
./drivers/usb/host/ohci-ep93xx.d \
./drivers/usb/host/ohci-exynos.d \
./drivers/usb/host/ohci-hcd.d \
./drivers/usb/host/ohci-hub.d \
./drivers/usb/host/ohci-jz4740.d \
./drivers/usb/host/ohci-mem.d \
./drivers/usb/host/ohci-nxp.d \
./drivers/usb/host/ohci-octeon.d \
./drivers/usb/host/ohci-omap.d \
./drivers/usb/host/ohci-omap3.d \
./drivers/usb/host/ohci-pci.d \
./drivers/usb/host/ohci-platform.d \
./drivers/usb/host/ohci-pnx8550.d \
./drivers/usb/host/ohci-ppc-of.d \
./drivers/usb/host/ohci-ppc-soc.d \
./drivers/usb/host/ohci-ps3.d \
./drivers/usb/host/ohci-pxa27x.d \
./drivers/usb/host/ohci-q.d \
./drivers/usb/host/ohci-s3c2410.d \
./drivers/usb/host/ohci-sa1111.d \
./drivers/usb/host/ohci-sh.d \
./drivers/usb/host/ohci-sm501.d \
./drivers/usb/host/ohci-spear.d \
./drivers/usb/host/ohci-ssb.d \
./drivers/usb/host/ohci-tmio.d \
./drivers/usb/host/ohci-xls.d \
./drivers/usb/host/oxu210hp-hcd.d \
./drivers/usb/host/pci-quirks.d \
./drivers/usb/host/r8a66597-hcd.d \
./drivers/usb/host/sl811-hcd.d \
./drivers/usb/host/sl811_cs.d \
./drivers/usb/host/u132-hcd.d \
./drivers/usb/host/uhci-debug.d \
./drivers/usb/host/uhci-grlib.d \
./drivers/usb/host/uhci-hcd.d \
./drivers/usb/host/uhci-hub.d \
./drivers/usb/host/uhci-pci.d \
./drivers/usb/host/uhci-q.d \
./drivers/usb/host/xhci-dbg.d \
./drivers/usb/host/xhci-hub.d \
./drivers/usb/host/xhci-mem.d \
./drivers/usb/host/xhci-pci.d \
./drivers/usb/host/xhci-plat.d \
./drivers/usb/host/xhci-ring.d \
./drivers/usb/host/xhci.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/usb/host/%.o: ../drivers/usb/host/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


