################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/usb/gadget/acm_ms.c \
../drivers/usb/gadget/amd5536udc.c \
../drivers/usb/gadget/android.c \
../drivers/usb/gadget/at91_udc.c \
../drivers/usb/gadget/atmel_usba_udc.c \
../drivers/usb/gadget/audio.c \
../drivers/usb/gadget/cdc2.c \
../drivers/usb/gadget/ci13xxx_msm.c \
../drivers/usb/gadget/ci13xxx_pci.c \
../drivers/usb/gadget/ci13xxx_udc.c \
../drivers/usb/gadget/composite.c \
../drivers/usb/gadget/config.c \
../drivers/usb/gadget/dbgp.c \
../drivers/usb/gadget/dummy_hcd.c \
../drivers/usb/gadget/epautoconf.c \
../drivers/usb/gadget/ether.c \
../drivers/usb/gadget/exynos_ss_udc.c \
../drivers/usb/gadget/f_accessory.c \
../drivers/usb/gadget/f_acm.c \
../drivers/usb/gadget/f_adb.c \
../drivers/usb/gadget/f_audio_source.c \
../drivers/usb/gadget/f_ecm.c \
../drivers/usb/gadget/f_eem.c \
../drivers/usb/gadget/f_fs.c \
../drivers/usb/gadget/f_hid.c \
../drivers/usb/gadget/f_loopback.c \
../drivers/usb/gadget/f_mass_storage.c \
../drivers/usb/gadget/f_midi.c \
../drivers/usb/gadget/f_mtp.c \
../drivers/usb/gadget/f_ncm.c \
../drivers/usb/gadget/f_obex.c \
../drivers/usb/gadget/f_phonet.c \
../drivers/usb/gadget/f_rndis.c \
../drivers/usb/gadget/f_serial.c \
../drivers/usb/gadget/f_sourcesink.c \
../drivers/usb/gadget/f_subset.c \
../drivers/usb/gadget/f_uac1.c \
../drivers/usb/gadget/f_uac2.c \
../drivers/usb/gadget/f_uvc.c \
../drivers/usb/gadget/file_storage.c \
../drivers/usb/gadget/fsl_mxc_udc.c \
../drivers/usb/gadget/fsl_qe_udc.c \
../drivers/usb/gadget/fsl_udc_core.c \
../drivers/usb/gadget/fusb300_udc.c \
../drivers/usb/gadget/g_ffs.c \
../drivers/usb/gadget/gmidi.c \
../drivers/usb/gadget/goku_udc.c \
../drivers/usb/gadget/hid.c \
../drivers/usb/gadget/imx_udc.c \
../drivers/usb/gadget/inode.c \
../drivers/usb/gadget/langwell_udc.c \
../drivers/usb/gadget/m66592-udc.c \
../drivers/usb/gadget/mass_storage.c \
../drivers/usb/gadget/multi.c \
../drivers/usb/gadget/mv_udc_core.c \
../drivers/usb/gadget/ncm.c \
../drivers/usb/gadget/net2272.c \
../drivers/usb/gadget/net2280.c \
../drivers/usb/gadget/nokia.c \
../drivers/usb/gadget/omap_udc.c \
../drivers/usb/gadget/pch_udc.c \
../drivers/usb/gadget/printer.c \
../drivers/usb/gadget/pxa25x_udc.c \
../drivers/usb/gadget/pxa27x_udc.c \
../drivers/usb/gadget/r8a66597-udc.c \
../drivers/usb/gadget/rndis.c \
../drivers/usb/gadget/s3c-hsotg.c \
../drivers/usb/gadget/s3c-hsudc.c \
../drivers/usb/gadget/s3c2410_udc.c \
../drivers/usb/gadget/s3c_udc_otg.c \
../drivers/usb/gadget/s3c_udc_otg_xfer_dma.c \
../drivers/usb/gadget/serial.c \
../drivers/usb/gadget/storage_common.c \
../drivers/usb/gadget/u_ether.c \
../drivers/usb/gadget/u_serial.c \
../drivers/usb/gadget/u_uac1.c \
../drivers/usb/gadget/udc-core.c \
../drivers/usb/gadget/usbstring.c \
../drivers/usb/gadget/uvc_queue.c \
../drivers/usb/gadget/uvc_v4l2.c \
../drivers/usb/gadget/uvc_video.c \
../drivers/usb/gadget/webcam.c \
../drivers/usb/gadget/zero.c 

OBJS += \
./drivers/usb/gadget/acm_ms.o \
./drivers/usb/gadget/amd5536udc.o \
./drivers/usb/gadget/android.o \
./drivers/usb/gadget/at91_udc.o \
./drivers/usb/gadget/atmel_usba_udc.o \
./drivers/usb/gadget/audio.o \
./drivers/usb/gadget/cdc2.o \
./drivers/usb/gadget/ci13xxx_msm.o \
./drivers/usb/gadget/ci13xxx_pci.o \
./drivers/usb/gadget/ci13xxx_udc.o \
./drivers/usb/gadget/composite.o \
./drivers/usb/gadget/config.o \
./drivers/usb/gadget/dbgp.o \
./drivers/usb/gadget/dummy_hcd.o \
./drivers/usb/gadget/epautoconf.o \
./drivers/usb/gadget/ether.o \
./drivers/usb/gadget/exynos_ss_udc.o \
./drivers/usb/gadget/f_accessory.o \
./drivers/usb/gadget/f_acm.o \
./drivers/usb/gadget/f_adb.o \
./drivers/usb/gadget/f_audio_source.o \
./drivers/usb/gadget/f_ecm.o \
./drivers/usb/gadget/f_eem.o \
./drivers/usb/gadget/f_fs.o \
./drivers/usb/gadget/f_hid.o \
./drivers/usb/gadget/f_loopback.o \
./drivers/usb/gadget/f_mass_storage.o \
./drivers/usb/gadget/f_midi.o \
./drivers/usb/gadget/f_mtp.o \
./drivers/usb/gadget/f_ncm.o \
./drivers/usb/gadget/f_obex.o \
./drivers/usb/gadget/f_phonet.o \
./drivers/usb/gadget/f_rndis.o \
./drivers/usb/gadget/f_serial.o \
./drivers/usb/gadget/f_sourcesink.o \
./drivers/usb/gadget/f_subset.o \
./drivers/usb/gadget/f_uac1.o \
./drivers/usb/gadget/f_uac2.o \
./drivers/usb/gadget/f_uvc.o \
./drivers/usb/gadget/file_storage.o \
./drivers/usb/gadget/fsl_mxc_udc.o \
./drivers/usb/gadget/fsl_qe_udc.o \
./drivers/usb/gadget/fsl_udc_core.o \
./drivers/usb/gadget/fusb300_udc.o \
./drivers/usb/gadget/g_ffs.o \
./drivers/usb/gadget/gmidi.o \
./drivers/usb/gadget/goku_udc.o \
./drivers/usb/gadget/hid.o \
./drivers/usb/gadget/imx_udc.o \
./drivers/usb/gadget/inode.o \
./drivers/usb/gadget/langwell_udc.o \
./drivers/usb/gadget/m66592-udc.o \
./drivers/usb/gadget/mass_storage.o \
./drivers/usb/gadget/multi.o \
./drivers/usb/gadget/mv_udc_core.o \
./drivers/usb/gadget/ncm.o \
./drivers/usb/gadget/net2272.o \
./drivers/usb/gadget/net2280.o \
./drivers/usb/gadget/nokia.o \
./drivers/usb/gadget/omap_udc.o \
./drivers/usb/gadget/pch_udc.o \
./drivers/usb/gadget/printer.o \
./drivers/usb/gadget/pxa25x_udc.o \
./drivers/usb/gadget/pxa27x_udc.o \
./drivers/usb/gadget/r8a66597-udc.o \
./drivers/usb/gadget/rndis.o \
./drivers/usb/gadget/s3c-hsotg.o \
./drivers/usb/gadget/s3c-hsudc.o \
./drivers/usb/gadget/s3c2410_udc.o \
./drivers/usb/gadget/s3c_udc_otg.o \
./drivers/usb/gadget/s3c_udc_otg_xfer_dma.o \
./drivers/usb/gadget/serial.o \
./drivers/usb/gadget/storage_common.o \
./drivers/usb/gadget/u_ether.o \
./drivers/usb/gadget/u_serial.o \
./drivers/usb/gadget/u_uac1.o \
./drivers/usb/gadget/udc-core.o \
./drivers/usb/gadget/usbstring.o \
./drivers/usb/gadget/uvc_queue.o \
./drivers/usb/gadget/uvc_v4l2.o \
./drivers/usb/gadget/uvc_video.o \
./drivers/usb/gadget/webcam.o \
./drivers/usb/gadget/zero.o 

C_DEPS += \
./drivers/usb/gadget/acm_ms.d \
./drivers/usb/gadget/amd5536udc.d \
./drivers/usb/gadget/android.d \
./drivers/usb/gadget/at91_udc.d \
./drivers/usb/gadget/atmel_usba_udc.d \
./drivers/usb/gadget/audio.d \
./drivers/usb/gadget/cdc2.d \
./drivers/usb/gadget/ci13xxx_msm.d \
./drivers/usb/gadget/ci13xxx_pci.d \
./drivers/usb/gadget/ci13xxx_udc.d \
./drivers/usb/gadget/composite.d \
./drivers/usb/gadget/config.d \
./drivers/usb/gadget/dbgp.d \
./drivers/usb/gadget/dummy_hcd.d \
./drivers/usb/gadget/epautoconf.d \
./drivers/usb/gadget/ether.d \
./drivers/usb/gadget/exynos_ss_udc.d \
./drivers/usb/gadget/f_accessory.d \
./drivers/usb/gadget/f_acm.d \
./drivers/usb/gadget/f_adb.d \
./drivers/usb/gadget/f_audio_source.d \
./drivers/usb/gadget/f_ecm.d \
./drivers/usb/gadget/f_eem.d \
./drivers/usb/gadget/f_fs.d \
./drivers/usb/gadget/f_hid.d \
./drivers/usb/gadget/f_loopback.d \
./drivers/usb/gadget/f_mass_storage.d \
./drivers/usb/gadget/f_midi.d \
./drivers/usb/gadget/f_mtp.d \
./drivers/usb/gadget/f_ncm.d \
./drivers/usb/gadget/f_obex.d \
./drivers/usb/gadget/f_phonet.d \
./drivers/usb/gadget/f_rndis.d \
./drivers/usb/gadget/f_serial.d \
./drivers/usb/gadget/f_sourcesink.d \
./drivers/usb/gadget/f_subset.d \
./drivers/usb/gadget/f_uac1.d \
./drivers/usb/gadget/f_uac2.d \
./drivers/usb/gadget/f_uvc.d \
./drivers/usb/gadget/file_storage.d \
./drivers/usb/gadget/fsl_mxc_udc.d \
./drivers/usb/gadget/fsl_qe_udc.d \
./drivers/usb/gadget/fsl_udc_core.d \
./drivers/usb/gadget/fusb300_udc.d \
./drivers/usb/gadget/g_ffs.d \
./drivers/usb/gadget/gmidi.d \
./drivers/usb/gadget/goku_udc.d \
./drivers/usb/gadget/hid.d \
./drivers/usb/gadget/imx_udc.d \
./drivers/usb/gadget/inode.d \
./drivers/usb/gadget/langwell_udc.d \
./drivers/usb/gadget/m66592-udc.d \
./drivers/usb/gadget/mass_storage.d \
./drivers/usb/gadget/multi.d \
./drivers/usb/gadget/mv_udc_core.d \
./drivers/usb/gadget/ncm.d \
./drivers/usb/gadget/net2272.d \
./drivers/usb/gadget/net2280.d \
./drivers/usb/gadget/nokia.d \
./drivers/usb/gadget/omap_udc.d \
./drivers/usb/gadget/pch_udc.d \
./drivers/usb/gadget/printer.d \
./drivers/usb/gadget/pxa25x_udc.d \
./drivers/usb/gadget/pxa27x_udc.d \
./drivers/usb/gadget/r8a66597-udc.d \
./drivers/usb/gadget/rndis.d \
./drivers/usb/gadget/s3c-hsotg.d \
./drivers/usb/gadget/s3c-hsudc.d \
./drivers/usb/gadget/s3c2410_udc.d \
./drivers/usb/gadget/s3c_udc_otg.d \
./drivers/usb/gadget/s3c_udc_otg_xfer_dma.d \
./drivers/usb/gadget/serial.d \
./drivers/usb/gadget/storage_common.d \
./drivers/usb/gadget/u_ether.d \
./drivers/usb/gadget/u_serial.d \
./drivers/usb/gadget/u_uac1.d \
./drivers/usb/gadget/udc-core.d \
./drivers/usb/gadget/usbstring.d \
./drivers/usb/gadget/uvc_queue.d \
./drivers/usb/gadget/uvc_v4l2.d \
./drivers/usb/gadget/uvc_video.d \
./drivers/usb/gadget/webcam.d \
./drivers/usb/gadget/zero.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/usb/gadget/%.o: ../drivers/usb/gadget/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


