################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/video/built-in.o \
../drivers/video/cfbcopyarea.o \
../drivers/video/cfbfillrect.o \
../drivers/video/cfbimgblt.o \
../drivers/video/fb.o \
../drivers/video/fb_notify.o \
../drivers/video/fbcmap.o \
../drivers/video/fbcvt.o \
../drivers/video/fbmem.o \
../drivers/video/fbmon.o \
../drivers/video/fbsysfs.o \
../drivers/video/modedb.o \
../drivers/video/nxp-fb.o 

C_SRCS += \
../drivers/video/68328fb.c \
../drivers/video/acornfb.c \
../drivers/video/amba-clcd.c \
../drivers/video/amifb.c \
../drivers/video/arcfb.c \
../drivers/video/arkfb.c \
../drivers/video/asiliantfb.c \
../drivers/video/atafb.c \
../drivers/video/atafb_iplan2p2.c \
../drivers/video/atafb_iplan2p4.c \
../drivers/video/atafb_iplan2p8.c \
../drivers/video/atafb_mfb.c \
../drivers/video/atmel_lcdfb.c \
../drivers/video/au1100fb.c \
../drivers/video/au1200fb.c \
../drivers/video/bf537-lq035.c \
../drivers/video/bf54x-lq043fb.c \
../drivers/video/bfin-lq035q1-fb.c \
../drivers/video/bfin-t350mcqb-fb.c \
../drivers/video/bfin_adv7393fb.c \
../drivers/video/broadsheetfb.c \
../drivers/video/bw2.c \
../drivers/video/c2p_iplan2.c \
../drivers/video/c2p_planar.c \
../drivers/video/carminefb.c \
../drivers/video/cfbcopyarea.c \
../drivers/video/cfbfillrect.c \
../drivers/video/cfbimgblt.c \
../drivers/video/cg14.c \
../drivers/video/cg3.c \
../drivers/video/cg6.c \
../drivers/video/chipsfb.c \
../drivers/video/cirrusfb.c \
../drivers/video/clps711xfb.c \
../drivers/video/cobalt_lcdfb.c \
../drivers/video/controlfb.c \
../drivers/video/cyber2000fb.c \
../drivers/video/da8xx-fb.c \
../drivers/video/dnfb.c \
../drivers/video/efifb.c \
../drivers/video/ep93xx-fb.c \
../drivers/video/epson1355fb.c \
../drivers/video/fb-puv3.c \
../drivers/video/fb_ddc.c \
../drivers/video/fb_defio.c \
../drivers/video/fb_notify.c \
../drivers/video/fb_sys_fops.c \
../drivers/video/fbcmap.c \
../drivers/video/fbcvt.c \
../drivers/video/fbmem.c \
../drivers/video/fbmon.c \
../drivers/video/fbsysfs.c \
../drivers/video/ffb.c \
../drivers/video/fm2fb.c \
../drivers/video/fsl-diu-fb.c \
../drivers/video/g364fb.c \
../drivers/video/gbefb.c \
../drivers/video/grvga.c \
../drivers/video/gxt4500.c \
../drivers/video/hecubafb.c \
../drivers/video/hgafb.c \
../drivers/video/hitfb.c \
../drivers/video/hpfb.c \
../drivers/video/i740fb.c \
../drivers/video/igafb.c \
../drivers/video/imsttfb.c \
../drivers/video/imxfb.c \
../drivers/video/jz4740_fb.c \
../drivers/video/leo.c \
../drivers/video/macfb.c \
../drivers/video/macmodes.c \
../drivers/video/maxinefb.c \
../drivers/video/metronomefb.c \
../drivers/video/modedb.c \
../drivers/video/mx3fb.c \
../drivers/video/mxsfb.c \
../drivers/video/n411.c \
../drivers/video/neofb.c \
../drivers/video/nuc900fb.c \
../drivers/video/nxp-fb.c \
../drivers/video/offb.c \
../drivers/video/output.c \
../drivers/video/p9100.c \
../drivers/video/platinumfb.c \
../drivers/video/pm2fb.c \
../drivers/video/pm3fb.c \
../drivers/video/pmag-aa-fb.c \
../drivers/video/pmag-ba-fb.c \
../drivers/video/pmagb-b-fb.c \
../drivers/video/ps3fb.c \
../drivers/video/pvr2fb.c \
../drivers/video/pxa168fb.c \
../drivers/video/pxa3xx-gcu.c \
../drivers/video/pxafb.c \
../drivers/video/q40fb.c \
../drivers/video/s1d13xxxfb.c \
../drivers/video/s3c-fb.c \
../drivers/video/s3c2410fb.c \
../drivers/video/s3fb.c \
../drivers/video/s5p-dp-core.c \
../drivers/video/s5p-dp-reg.c \
../drivers/video/s5p_mipi_dsi.c \
../drivers/video/s5p_mipi_dsi_lowlevel.c \
../drivers/video/sa1100fb.c \
../drivers/video/sbuslib.c \
../drivers/video/sgivwfb.c \
../drivers/video/sh7760fb.c \
../drivers/video/sh_mipi_dsi.c \
../drivers/video/sh_mobile_hdmi.c \
../drivers/video/sh_mobile_lcdcfb.c \
../drivers/video/sh_mobile_meram.c \
../drivers/video/skeletonfb.c \
../drivers/video/sm501fb.c \
../drivers/video/smscufx.c \
../drivers/video/sstfb.c \
../drivers/video/stifb.c \
../drivers/video/sunxvr1000.c \
../drivers/video/sunxvr2500.c \
../drivers/video/sunxvr500.c \
../drivers/video/svgalib.c \
../drivers/video/syscopyarea.c \
../drivers/video/sysfillrect.c \
../drivers/video/sysimgblt.c \
../drivers/video/tcx.c \
../drivers/video/tdfxfb.c \
../drivers/video/tgafb.c \
../drivers/video/tmiofb.c \
../drivers/video/tridentfb.c \
../drivers/video/udlfb.c \
../drivers/video/uvesafb.c \
../drivers/video/valkyriefb.c \
../drivers/video/vesafb.c \
../drivers/video/vfb.c \
../drivers/video/vga16fb.c \
../drivers/video/vgastate.c \
../drivers/video/vt8500lcdfb.c \
../drivers/video/vt8623fb.c \
../drivers/video/w100fb.c \
../drivers/video/wm8505fb.c \
../drivers/video/wmt_ge_rops.c \
../drivers/video/xen-fbfront.c \
../drivers/video/xilinxfb.c 

OBJS += \
./drivers/video/68328fb.o \
./drivers/video/acornfb.o \
./drivers/video/amba-clcd.o \
./drivers/video/amifb.o \
./drivers/video/arcfb.o \
./drivers/video/arkfb.o \
./drivers/video/asiliantfb.o \
./drivers/video/atafb.o \
./drivers/video/atafb_iplan2p2.o \
./drivers/video/atafb_iplan2p4.o \
./drivers/video/atafb_iplan2p8.o \
./drivers/video/atafb_mfb.o \
./drivers/video/atmel_lcdfb.o \
./drivers/video/au1100fb.o \
./drivers/video/au1200fb.o \
./drivers/video/bf537-lq035.o \
./drivers/video/bf54x-lq043fb.o \
./drivers/video/bfin-lq035q1-fb.o \
./drivers/video/bfin-t350mcqb-fb.o \
./drivers/video/bfin_adv7393fb.o \
./drivers/video/broadsheetfb.o \
./drivers/video/bw2.o \
./drivers/video/c2p_iplan2.o \
./drivers/video/c2p_planar.o \
./drivers/video/carminefb.o \
./drivers/video/cfbcopyarea.o \
./drivers/video/cfbfillrect.o \
./drivers/video/cfbimgblt.o \
./drivers/video/cg14.o \
./drivers/video/cg3.o \
./drivers/video/cg6.o \
./drivers/video/chipsfb.o \
./drivers/video/cirrusfb.o \
./drivers/video/clps711xfb.o \
./drivers/video/cobalt_lcdfb.o \
./drivers/video/controlfb.o \
./drivers/video/cyber2000fb.o \
./drivers/video/da8xx-fb.o \
./drivers/video/dnfb.o \
./drivers/video/efifb.o \
./drivers/video/ep93xx-fb.o \
./drivers/video/epson1355fb.o \
./drivers/video/fb-puv3.o \
./drivers/video/fb_ddc.o \
./drivers/video/fb_defio.o \
./drivers/video/fb_notify.o \
./drivers/video/fb_sys_fops.o \
./drivers/video/fbcmap.o \
./drivers/video/fbcvt.o \
./drivers/video/fbmem.o \
./drivers/video/fbmon.o \
./drivers/video/fbsysfs.o \
./drivers/video/ffb.o \
./drivers/video/fm2fb.o \
./drivers/video/fsl-diu-fb.o \
./drivers/video/g364fb.o \
./drivers/video/gbefb.o \
./drivers/video/grvga.o \
./drivers/video/gxt4500.o \
./drivers/video/hecubafb.o \
./drivers/video/hgafb.o \
./drivers/video/hitfb.o \
./drivers/video/hpfb.o \
./drivers/video/i740fb.o \
./drivers/video/igafb.o \
./drivers/video/imsttfb.o \
./drivers/video/imxfb.o \
./drivers/video/jz4740_fb.o \
./drivers/video/leo.o \
./drivers/video/macfb.o \
./drivers/video/macmodes.o \
./drivers/video/maxinefb.o \
./drivers/video/metronomefb.o \
./drivers/video/modedb.o \
./drivers/video/mx3fb.o \
./drivers/video/mxsfb.o \
./drivers/video/n411.o \
./drivers/video/neofb.o \
./drivers/video/nuc900fb.o \
./drivers/video/nxp-fb.o \
./drivers/video/offb.o \
./drivers/video/output.o \
./drivers/video/p9100.o \
./drivers/video/platinumfb.o \
./drivers/video/pm2fb.o \
./drivers/video/pm3fb.o \
./drivers/video/pmag-aa-fb.o \
./drivers/video/pmag-ba-fb.o \
./drivers/video/pmagb-b-fb.o \
./drivers/video/ps3fb.o \
./drivers/video/pvr2fb.o \
./drivers/video/pxa168fb.o \
./drivers/video/pxa3xx-gcu.o \
./drivers/video/pxafb.o \
./drivers/video/q40fb.o \
./drivers/video/s1d13xxxfb.o \
./drivers/video/s3c-fb.o \
./drivers/video/s3c2410fb.o \
./drivers/video/s3fb.o \
./drivers/video/s5p-dp-core.o \
./drivers/video/s5p-dp-reg.o \
./drivers/video/s5p_mipi_dsi.o \
./drivers/video/s5p_mipi_dsi_lowlevel.o \
./drivers/video/sa1100fb.o \
./drivers/video/sbuslib.o \
./drivers/video/sgivwfb.o \
./drivers/video/sh7760fb.o \
./drivers/video/sh_mipi_dsi.o \
./drivers/video/sh_mobile_hdmi.o \
./drivers/video/sh_mobile_lcdcfb.o \
./drivers/video/sh_mobile_meram.o \
./drivers/video/skeletonfb.o \
./drivers/video/sm501fb.o \
./drivers/video/smscufx.o \
./drivers/video/sstfb.o \
./drivers/video/stifb.o \
./drivers/video/sunxvr1000.o \
./drivers/video/sunxvr2500.o \
./drivers/video/sunxvr500.o \
./drivers/video/svgalib.o \
./drivers/video/syscopyarea.o \
./drivers/video/sysfillrect.o \
./drivers/video/sysimgblt.o \
./drivers/video/tcx.o \
./drivers/video/tdfxfb.o \
./drivers/video/tgafb.o \
./drivers/video/tmiofb.o \
./drivers/video/tridentfb.o \
./drivers/video/udlfb.o \
./drivers/video/uvesafb.o \
./drivers/video/valkyriefb.o \
./drivers/video/vesafb.o \
./drivers/video/vfb.o \
./drivers/video/vga16fb.o \
./drivers/video/vgastate.o \
./drivers/video/vt8500lcdfb.o \
./drivers/video/vt8623fb.o \
./drivers/video/w100fb.o \
./drivers/video/wm8505fb.o \
./drivers/video/wmt_ge_rops.o \
./drivers/video/xen-fbfront.o \
./drivers/video/xilinxfb.o 

C_DEPS += \
./drivers/video/68328fb.d \
./drivers/video/acornfb.d \
./drivers/video/amba-clcd.d \
./drivers/video/amifb.d \
./drivers/video/arcfb.d \
./drivers/video/arkfb.d \
./drivers/video/asiliantfb.d \
./drivers/video/atafb.d \
./drivers/video/atafb_iplan2p2.d \
./drivers/video/atafb_iplan2p4.d \
./drivers/video/atafb_iplan2p8.d \
./drivers/video/atafb_mfb.d \
./drivers/video/atmel_lcdfb.d \
./drivers/video/au1100fb.d \
./drivers/video/au1200fb.d \
./drivers/video/bf537-lq035.d \
./drivers/video/bf54x-lq043fb.d \
./drivers/video/bfin-lq035q1-fb.d \
./drivers/video/bfin-t350mcqb-fb.d \
./drivers/video/bfin_adv7393fb.d \
./drivers/video/broadsheetfb.d \
./drivers/video/bw2.d \
./drivers/video/c2p_iplan2.d \
./drivers/video/c2p_planar.d \
./drivers/video/carminefb.d \
./drivers/video/cfbcopyarea.d \
./drivers/video/cfbfillrect.d \
./drivers/video/cfbimgblt.d \
./drivers/video/cg14.d \
./drivers/video/cg3.d \
./drivers/video/cg6.d \
./drivers/video/chipsfb.d \
./drivers/video/cirrusfb.d \
./drivers/video/clps711xfb.d \
./drivers/video/cobalt_lcdfb.d \
./drivers/video/controlfb.d \
./drivers/video/cyber2000fb.d \
./drivers/video/da8xx-fb.d \
./drivers/video/dnfb.d \
./drivers/video/efifb.d \
./drivers/video/ep93xx-fb.d \
./drivers/video/epson1355fb.d \
./drivers/video/fb-puv3.d \
./drivers/video/fb_ddc.d \
./drivers/video/fb_defio.d \
./drivers/video/fb_notify.d \
./drivers/video/fb_sys_fops.d \
./drivers/video/fbcmap.d \
./drivers/video/fbcvt.d \
./drivers/video/fbmem.d \
./drivers/video/fbmon.d \
./drivers/video/fbsysfs.d \
./drivers/video/ffb.d \
./drivers/video/fm2fb.d \
./drivers/video/fsl-diu-fb.d \
./drivers/video/g364fb.d \
./drivers/video/gbefb.d \
./drivers/video/grvga.d \
./drivers/video/gxt4500.d \
./drivers/video/hecubafb.d \
./drivers/video/hgafb.d \
./drivers/video/hitfb.d \
./drivers/video/hpfb.d \
./drivers/video/i740fb.d \
./drivers/video/igafb.d \
./drivers/video/imsttfb.d \
./drivers/video/imxfb.d \
./drivers/video/jz4740_fb.d \
./drivers/video/leo.d \
./drivers/video/macfb.d \
./drivers/video/macmodes.d \
./drivers/video/maxinefb.d \
./drivers/video/metronomefb.d \
./drivers/video/modedb.d \
./drivers/video/mx3fb.d \
./drivers/video/mxsfb.d \
./drivers/video/n411.d \
./drivers/video/neofb.d \
./drivers/video/nuc900fb.d \
./drivers/video/nxp-fb.d \
./drivers/video/offb.d \
./drivers/video/output.d \
./drivers/video/p9100.d \
./drivers/video/platinumfb.d \
./drivers/video/pm2fb.d \
./drivers/video/pm3fb.d \
./drivers/video/pmag-aa-fb.d \
./drivers/video/pmag-ba-fb.d \
./drivers/video/pmagb-b-fb.d \
./drivers/video/ps3fb.d \
./drivers/video/pvr2fb.d \
./drivers/video/pxa168fb.d \
./drivers/video/pxa3xx-gcu.d \
./drivers/video/pxafb.d \
./drivers/video/q40fb.d \
./drivers/video/s1d13xxxfb.d \
./drivers/video/s3c-fb.d \
./drivers/video/s3c2410fb.d \
./drivers/video/s3fb.d \
./drivers/video/s5p-dp-core.d \
./drivers/video/s5p-dp-reg.d \
./drivers/video/s5p_mipi_dsi.d \
./drivers/video/s5p_mipi_dsi_lowlevel.d \
./drivers/video/sa1100fb.d \
./drivers/video/sbuslib.d \
./drivers/video/sgivwfb.d \
./drivers/video/sh7760fb.d \
./drivers/video/sh_mipi_dsi.d \
./drivers/video/sh_mobile_hdmi.d \
./drivers/video/sh_mobile_lcdcfb.d \
./drivers/video/sh_mobile_meram.d \
./drivers/video/skeletonfb.d \
./drivers/video/sm501fb.d \
./drivers/video/smscufx.d \
./drivers/video/sstfb.d \
./drivers/video/stifb.d \
./drivers/video/sunxvr1000.d \
./drivers/video/sunxvr2500.d \
./drivers/video/sunxvr500.d \
./drivers/video/svgalib.d \
./drivers/video/syscopyarea.d \
./drivers/video/sysfillrect.d \
./drivers/video/sysimgblt.d \
./drivers/video/tcx.d \
./drivers/video/tdfxfb.d \
./drivers/video/tgafb.d \
./drivers/video/tmiofb.d \
./drivers/video/tridentfb.d \
./drivers/video/udlfb.d \
./drivers/video/uvesafb.d \
./drivers/video/valkyriefb.d \
./drivers/video/vesafb.d \
./drivers/video/vfb.d \
./drivers/video/vga16fb.d \
./drivers/video/vgastate.d \
./drivers/video/vt8500lcdfb.d \
./drivers/video/vt8623fb.d \
./drivers/video/w100fb.d \
./drivers/video/wm8505fb.d \
./drivers/video/wmt_ge_rops.d \
./drivers/video/xen-fbfront.d \
./drivers/video/xilinxfb.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/video/%.o: ../drivers/video/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


