
#include <mach/cfg_type.h>
#include <mach/gpio/cfg_gpio_vtk.h>

const U32 io_pad_vtk[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_VTK, PAD_GPIOA01_VTK, PAD_GPIOA02_VTK, PAD_GPIOA03_VTK,
	PAD_GPIOA04_VTK, PAD_GPIOA05_VTK, PAD_GPIOA06_VTK, PAD_GPIOA07_VTK,
	PAD_GPIOA08_VTK, PAD_GPIOA09_VTK, PAD_GPIOA10_VTK, PAD_GPIOA11_VTK,
	PAD_GPIOA12_VTK, PAD_GPIOA13_VTK, PAD_GPIOA14_VTK, PAD_GPIOA15_VTK,
	PAD_GPIOA16_VTK, PAD_GPIOA17_VTK, PAD_GPIOA18_VTK, PAD_GPIOA19_VTK,
	PAD_GPIOA20_VTK, PAD_GPIOA21_VTK, PAD_GPIOA22_VTK, PAD_GPIOA23_VTK,
	PAD_GPIOA24_VTK, PAD_GPIOA25_VTK, PAD_GPIOA26_VTK, PAD_GPIOA27_VTK,
	PAD_GPIOA28_VTK, PAD_GPIOA29_VTK, PAD_GPIOA30_VTK, PAD_GPIOA31_VTK,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_VTK, PAD_GPIOB01_VTK, PAD_GPIOB02_VTK, PAD_GPIOB03_VTK,
	PAD_GPIOB04_VTK, PAD_GPIOB05_VTK, PAD_GPIOB06_VTK, PAD_GPIOB07_VTK,
	PAD_GPIOB08_VTK, PAD_GPIOB09_VTK, PAD_GPIOB10_VTK, PAD_GPIOB11_VTK,
	PAD_GPIOB12_VTK, PAD_GPIOB13_VTK, PAD_GPIOB14_VTK, PAD_GPIOB15_VTK,
	PAD_GPIOB16_VTK, PAD_GPIOB17_VTK, PAD_GPIOB18_VTK, PAD_GPIOB19_VTK,
	PAD_GPIOB20_VTK, PAD_GPIOB21_VTK, PAD_GPIOB22_VTK, PAD_GPIOB23_VTK,
	PAD_GPIOB24_VTK, PAD_GPIOB25_VTK, PAD_GPIOB26_VTK, PAD_GPIOB27_VTK,
	PAD_GPIOB28_VTK, PAD_GPIOB29_VTK, PAD_GPIOB30_VTK, PAD_GPIOB31_VTK,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_VTK, PAD_GPIOC01_VTK, PAD_GPIOC02_VTK, PAD_GPIOC03_VTK,
	PAD_GPIOC04_VTK, PAD_GPIOC05_VTK, PAD_GPIOC06_VTK, PAD_GPIOC07_VTK,
	PAD_GPIOC08_VTK, PAD_GPIOC09_VTK, PAD_GPIOC10_VTK, PAD_GPIOC11_VTK,
	PAD_GPIOC12_VTK, PAD_GPIOC13_VTK, PAD_GPIOC14_VTK, PAD_GPIOC15_VTK,
	PAD_GPIOC16_VTK, PAD_GPIOC17_VTK, PAD_GPIOC18_VTK, PAD_GPIOC19_VTK,
	PAD_GPIOC20_VTK, PAD_GPIOC21_VTK, PAD_GPIOC22_VTK, PAD_GPIOC23_VTK,
	PAD_GPIOC24_VTK, PAD_GPIOC25_VTK, PAD_GPIOC26_VTK, PAD_GPIOC27_VTK,
	PAD_GPIOC28_VTK, PAD_GPIOC29_VTK, PAD_GPIOC30_VTK, PAD_GPIOC31_VTK,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_VTK, PAD_GPIOD01_VTK, PAD_GPIOD02_VTK, PAD_GPIOD03_VTK,
	PAD_GPIOD04_VTK, PAD_GPIOD05_VTK, PAD_GPIOD06_VTK, PAD_GPIOD07_VTK,
	PAD_GPIOD08_VTK, PAD_GPIOD09_VTK, PAD_GPIOD10_VTK, PAD_GPIOD11_VTK,
	PAD_GPIOD12_VTK, PAD_GPIOD13_VTK, PAD_GPIOD14_VTK, PAD_GPIOD15_VTK,
	PAD_GPIOD16_VTK, PAD_GPIOD17_VTK, PAD_GPIOD18_VTK, PAD_GPIOD19_VTK,
	PAD_GPIOD20_VTK, PAD_GPIOD21_VTK, PAD_GPIOD22_VTK, PAD_GPIOD23_VTK,
	PAD_GPIOD24_VTK, 0,                0,                0,
	0,               0,                0,                0,
	}
};

const U32 alv_pad_vtk[ALVPADS] = {
	PAD_GPIOALV0_VTK, PAD_GPIOALV1_VTK, PAD_GPIOALV2_VTK, 
	PAD_GPIOALV3_VTK, PAD_GPIOALV4_VTK, PAD_GPIOALV5_VTK
};

const U32 bus_pad_vtk[6] = {
	PAD_BUS_STATIC_CNTL_VTK, PAD_BUS_STATIC_ADDR_VTK,  PAD_BUS_STATIC_DATA_VTK,
	PAD_BUS_VSYNC_VTK, PAD_BUS_HSYNC_VTK, PAD_BUS_DE_VTK
};

