
#include <mach/cfg_type.h>
#include <mach/gpio/cfg_gpio_lowcost_alpha.h>

const U32 io_pad_lowcost_alpha[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_LOWCOST_ALPHA, PAD_GPIOA01_LOWCOST_ALPHA, PAD_GPIOA02_LOWCOST_ALPHA, PAD_GPIOA03_LOWCOST_ALPHA,
	PAD_GPIOA04_LOWCOST_ALPHA, PAD_GPIOA05_LOWCOST_ALPHA, PAD_GPIOA06_LOWCOST_ALPHA, PAD_GPIOA07_LOWCOST_ALPHA,
	PAD_GPIOA08_LOWCOST_ALPHA, PAD_GPIOA09_LOWCOST_ALPHA, PAD_GPIOA10_LOWCOST_ALPHA, PAD_GPIOA11_LOWCOST_ALPHA,
	PAD_GPIOA12_LOWCOST_ALPHA, PAD_GPIOA13_LOWCOST_ALPHA, PAD_GPIOA14_LOWCOST_ALPHA, PAD_GPIOA15_LOWCOST_ALPHA,
	PAD_GPIOA16_LOWCOST_ALPHA, PAD_GPIOA17_LOWCOST_ALPHA, PAD_GPIOA18_LOWCOST_ALPHA, PAD_GPIOA19_LOWCOST_ALPHA,
	PAD_GPIOA20_LOWCOST_ALPHA, PAD_GPIOA21_LOWCOST_ALPHA, PAD_GPIOA22_LOWCOST_ALPHA, PAD_GPIOA23_LOWCOST_ALPHA,
	PAD_GPIOA24_LOWCOST_ALPHA, PAD_GPIOA25_LOWCOST_ALPHA, PAD_GPIOA26_LOWCOST_ALPHA, PAD_GPIOA27_LOWCOST_ALPHA,
	PAD_GPIOA28_LOWCOST_ALPHA, PAD_GPIOA29_LOWCOST_ALPHA, PAD_GPIOA30_LOWCOST_ALPHA, PAD_GPIOA31_LOWCOST_ALPHA,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_LOWCOST_ALPHA, PAD_GPIOB01_LOWCOST_ALPHA, PAD_GPIOB02_LOWCOST_ALPHA, PAD_GPIOB03_LOWCOST_ALPHA,
	PAD_GPIOB04_LOWCOST_ALPHA, PAD_GPIOB05_LOWCOST_ALPHA, PAD_GPIOB06_LOWCOST_ALPHA, PAD_GPIOB07_LOWCOST_ALPHA,
	PAD_GPIOB08_LOWCOST_ALPHA, PAD_GPIOB09_LOWCOST_ALPHA, PAD_GPIOB10_LOWCOST_ALPHA, PAD_GPIOB11_LOWCOST_ALPHA,
	PAD_GPIOB12_LOWCOST_ALPHA, PAD_GPIOB13_LOWCOST_ALPHA, PAD_GPIOB14_LOWCOST_ALPHA, PAD_GPIOB15_LOWCOST_ALPHA,
	PAD_GPIOB16_LOWCOST_ALPHA, PAD_GPIOB17_LOWCOST_ALPHA, PAD_GPIOB18_LOWCOST_ALPHA, PAD_GPIOB19_LOWCOST_ALPHA,
	PAD_GPIOB20_LOWCOST_ALPHA, PAD_GPIOB21_LOWCOST_ALPHA, PAD_GPIOB22_LOWCOST_ALPHA, PAD_GPIOB23_LOWCOST_ALPHA,
	PAD_GPIOB24_LOWCOST_ALPHA, PAD_GPIOB25_LOWCOST_ALPHA, PAD_GPIOB26_LOWCOST_ALPHA, PAD_GPIOB27_LOWCOST_ALPHA,
	PAD_GPIOB28_LOWCOST_ALPHA, PAD_GPIOB29_LOWCOST_ALPHA, PAD_GPIOB30_LOWCOST_ALPHA, PAD_GPIOB31_LOWCOST_ALPHA,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_LOWCOST_ALPHA, PAD_GPIOC01_LOWCOST_ALPHA, PAD_GPIOC02_LOWCOST_ALPHA, PAD_GPIOC03_LOWCOST_ALPHA,
	PAD_GPIOC04_LOWCOST_ALPHA, PAD_GPIOC05_LOWCOST_ALPHA, PAD_GPIOC06_LOWCOST_ALPHA, PAD_GPIOC07_LOWCOST_ALPHA,
	PAD_GPIOC08_LOWCOST_ALPHA, PAD_GPIOC09_LOWCOST_ALPHA, PAD_GPIOC10_LOWCOST_ALPHA, PAD_GPIOC11_LOWCOST_ALPHA,
	PAD_GPIOC12_LOWCOST_ALPHA, PAD_GPIOC13_LOWCOST_ALPHA, PAD_GPIOC14_LOWCOST_ALPHA, PAD_GPIOC15_LOWCOST_ALPHA,
	PAD_GPIOC16_LOWCOST_ALPHA, PAD_GPIOC17_LOWCOST_ALPHA, PAD_GPIOC18_LOWCOST_ALPHA, PAD_GPIOC19_LOWCOST_ALPHA,
	PAD_GPIOC20_LOWCOST_ALPHA, PAD_GPIOC21_LOWCOST_ALPHA, PAD_GPIOC22_LOWCOST_ALPHA, PAD_GPIOC23_LOWCOST_ALPHA,
	PAD_GPIOC24_LOWCOST_ALPHA, PAD_GPIOC25_LOWCOST_ALPHA, PAD_GPIOC26_LOWCOST_ALPHA, PAD_GPIOC27_LOWCOST_ALPHA,
	PAD_GPIOC28_LOWCOST_ALPHA, PAD_GPIOC29_LOWCOST_ALPHA, PAD_GPIOC30_LOWCOST_ALPHA, PAD_GPIOC31_LOWCOST_ALPHA,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_LOWCOST_ALPHA, PAD_GPIOD01_LOWCOST_ALPHA, PAD_GPIOD02_LOWCOST_ALPHA, PAD_GPIOD03_LOWCOST_ALPHA,
	PAD_GPIOD04_LOWCOST_ALPHA, PAD_GPIOD05_LOWCOST_ALPHA, PAD_GPIOD06_LOWCOST_ALPHA, PAD_GPIOD07_LOWCOST_ALPHA,
	PAD_GPIOD08_LOWCOST_ALPHA, PAD_GPIOD09_LOWCOST_ALPHA, PAD_GPIOD10_LOWCOST_ALPHA, PAD_GPIOD11_LOWCOST_ALPHA,
	PAD_GPIOD12_LOWCOST_ALPHA, PAD_GPIOD13_LOWCOST_ALPHA, PAD_GPIOD14_LOWCOST_ALPHA, PAD_GPIOD15_LOWCOST_ALPHA,
	PAD_GPIOD16_LOWCOST_ALPHA, PAD_GPIOD17_LOWCOST_ALPHA, PAD_GPIOD18_LOWCOST_ALPHA, PAD_GPIOD19_LOWCOST_ALPHA,
	PAD_GPIOD20_LOWCOST_ALPHA, PAD_GPIOD21_LOWCOST_ALPHA, PAD_GPIOD22_LOWCOST_ALPHA, PAD_GPIOD23_LOWCOST_ALPHA,
	PAD_GPIOD24_LOWCOST_ALPHA, PAD_GPIOD25_LOWCOST_ALPHA, PAD_GPIOD26_LOWCOST_ALPHA, PAD_GPIOD27_LOWCOST_ALPHA,
	PAD_GPIOD28_LOWCOST_ALPHA, PAD_GPIOD29_LOWCOST_ALPHA, PAD_GPIOD30_LOWCOST_ALPHA, PAD_GPIOD31_LOWCOST_ALPHA,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_LOWCOST_ALPHA, PAD_GPIOE01_LOWCOST_ALPHA, PAD_GPIOE02_LOWCOST_ALPHA, PAD_GPIOE03_LOWCOST_ALPHA,
	PAD_GPIOE04_LOWCOST_ALPHA, PAD_GPIOE05_LOWCOST_ALPHA, PAD_GPIOE06_LOWCOST_ALPHA, PAD_GPIOE07_LOWCOST_ALPHA,
	PAD_GPIOE08_LOWCOST_ALPHA, PAD_GPIOE09_LOWCOST_ALPHA, PAD_GPIOE10_LOWCOST_ALPHA, PAD_GPIOE11_LOWCOST_ALPHA,
	PAD_GPIOE12_LOWCOST_ALPHA, PAD_GPIOE13_LOWCOST_ALPHA, PAD_GPIOE14_LOWCOST_ALPHA, PAD_GPIOE15_LOWCOST_ALPHA,
	PAD_GPIOE16_LOWCOST_ALPHA, PAD_GPIOE17_LOWCOST_ALPHA, PAD_GPIOE18_LOWCOST_ALPHA, PAD_GPIOE19_LOWCOST_ALPHA,
	PAD_GPIOE20_LOWCOST_ALPHA, PAD_GPIOE21_LOWCOST_ALPHA, PAD_GPIOE22_LOWCOST_ALPHA, PAD_GPIOE23_LOWCOST_ALPHA,
	PAD_GPIOE24_LOWCOST_ALPHA, PAD_GPIOE25_LOWCOST_ALPHA, PAD_GPIOE26_LOWCOST_ALPHA, PAD_GPIOE27_LOWCOST_ALPHA,
	PAD_GPIOE28_LOWCOST_ALPHA, PAD_GPIOE29_LOWCOST_ALPHA, PAD_GPIOE30_LOWCOST_ALPHA, PAD_GPIOE31_LOWCOST_ALPHA,
	},
};

const U32 alv_pad_lowcost_alpha[ALVPADS] = 
{
	PAD_GPIOALV00_LOWCOST_ALPHA, PAD_GPIOALV01_LOWCOST_ALPHA, 
	PAD_GPIOALV02_LOWCOST_ALPHA, PAD_GPIOALV03_LOWCOST_ALPHA,
	PAD_GPIOALV04_LOWCOST_ALPHA, PAD_GPIOALV05_LOWCOST_ALPHA
	};

const U32 bus_pad_lowcost_alpha[6] = {
	PAD_BUS_STATIC_CNTL_LOWCOST_ALPHA, PAD_BUS_STATIC_ADDR_LOWCOST_ALPHA, PAD_BUS_STATIC_DATA_LOWCOST_ALPHA,
	PAD_BUS_VSYNC_LOWCOST_ALPHA, PAD_BUS_HSYNC_LOWCOST_ALPHA, PAD_BUS_DE_LOWCOST_ALPHA
};
