
#include <cfg_type.h>
#include <../../santiago/include/cfg_gpio_santiago.h>

const U32 io_pad_santiago[NUMBER_OF_GPIO_MODULE][32] = {
	/* GPIO group A */
	{
	PAD_GPIOA00_SANTIAGO, PAD_GPIOA01_SANTIAGO, PAD_GPIOA02_SANTIAGO, PAD_GPIOA03_SANTIAGO,
	PAD_GPIOA04_SANTIAGO, PAD_GPIOA05_SANTIAGO, PAD_GPIOA06_SANTIAGO, PAD_GPIOA07_SANTIAGO,
	PAD_GPIOA08_SANTIAGO, PAD_GPIOA09_SANTIAGO, PAD_GPIOA10_SANTIAGO, PAD_GPIOA11_SANTIAGO,
	PAD_GPIOA12_SANTIAGO, PAD_GPIOA13_SANTIAGO, PAD_GPIOA14_SANTIAGO, PAD_GPIOA15_SANTIAGO,
	PAD_GPIOA16_SANTIAGO, PAD_GPIOA17_SANTIAGO, PAD_GPIOA18_SANTIAGO, PAD_GPIOA19_SANTIAGO,
	PAD_GPIOA20_SANTIAGO, PAD_GPIOA21_SANTIAGO, PAD_GPIOA22_SANTIAGO, PAD_GPIOA23_SANTIAGO,
	PAD_GPIOA24_SANTIAGO, PAD_GPIOA25_SANTIAGO, PAD_GPIOA26_SANTIAGO, PAD_GPIOA27_SANTIAGO,
	PAD_GPIOA28_SANTIAGO, PAD_GPIOA29_SANTIAGO, PAD_GPIOA30_SANTIAGO, PAD_GPIOA31_SANTIAGO,
	},
	/* GPIO group B */
	{
	PAD_GPIOB00_SANTIAGO, PAD_GPIOB01_SANTIAGO, PAD_GPIOB02_SANTIAGO, PAD_GPIOB03_SANTIAGO,
	PAD_GPIOB04_SANTIAGO, PAD_GPIOB05_SANTIAGO, PAD_GPIOB06_SANTIAGO, PAD_GPIOB07_SANTIAGO,
	PAD_GPIOB08_SANTIAGO, PAD_GPIOB09_SANTIAGO, PAD_GPIOB10_SANTIAGO, PAD_GPIOB11_SANTIAGO,
	PAD_GPIOB12_SANTIAGO, PAD_GPIOB13_SANTIAGO, PAD_GPIOB14_SANTIAGO, PAD_GPIOB15_SANTIAGO,
	PAD_GPIOB16_SANTIAGO, PAD_GPIOB17_SANTIAGO, PAD_GPIOB18_SANTIAGO, PAD_GPIOB19_SANTIAGO,
	PAD_GPIOB20_SANTIAGO, PAD_GPIOB21_SANTIAGO, PAD_GPIOB22_SANTIAGO, PAD_GPIOB23_SANTIAGO,
	PAD_GPIOB24_SANTIAGO, PAD_GPIOB25_SANTIAGO, PAD_GPIOB26_SANTIAGO, PAD_GPIOB27_SANTIAGO,
	PAD_GPIOB28_SANTIAGO, PAD_GPIOB29_SANTIAGO, PAD_GPIOB30_SANTIAGO, PAD_GPIOB31_SANTIAGO,
	},
	/* GPIO group C */
	{
	PAD_GPIOC00_SANTIAGO, PAD_GPIOC01_SANTIAGO, PAD_GPIOC02_SANTIAGO, PAD_GPIOC03_SANTIAGO,
	PAD_GPIOC04_SANTIAGO, PAD_GPIOC05_SANTIAGO, PAD_GPIOC06_SANTIAGO, PAD_GPIOC07_SANTIAGO,
	PAD_GPIOC08_SANTIAGO, PAD_GPIOC09_SANTIAGO, PAD_GPIOC10_SANTIAGO, PAD_GPIOC11_SANTIAGO,
	PAD_GPIOC12_SANTIAGO, PAD_GPIOC13_SANTIAGO, PAD_GPIOC14_SANTIAGO, PAD_GPIOC15_SANTIAGO,
	PAD_GPIOC16_SANTIAGO, PAD_GPIOC17_SANTIAGO, PAD_GPIOC18_SANTIAGO, PAD_GPIOC19_SANTIAGO,
	PAD_GPIOC20_SANTIAGO, PAD_GPIOC21_SANTIAGO, PAD_GPIOC22_SANTIAGO, PAD_GPIOC23_SANTIAGO,
	PAD_GPIOC24_SANTIAGO, PAD_GPIOC25_SANTIAGO, PAD_GPIOC26_SANTIAGO, PAD_GPIOC27_SANTIAGO,
	PAD_GPIOC28_SANTIAGO, PAD_GPIOC29_SANTIAGO, PAD_GPIOC30_SANTIAGO, PAD_GPIOC31_SANTIAGO,
	},
	/* GPIO group D */
	{
	PAD_GPIOD00_SANTIAGO, PAD_GPIOD01_SANTIAGO, PAD_GPIOD02_SANTIAGO, PAD_GPIOD03_SANTIAGO,
	PAD_GPIOD04_SANTIAGO, PAD_GPIOD05_SANTIAGO, PAD_GPIOD06_SANTIAGO, PAD_GPIOD07_SANTIAGO,
	PAD_GPIOD08_SANTIAGO, PAD_GPIOD09_SANTIAGO, PAD_GPIOD10_SANTIAGO, PAD_GPIOD11_SANTIAGO,
	PAD_GPIOD12_SANTIAGO, PAD_GPIOD13_SANTIAGO, PAD_GPIOD14_SANTIAGO, PAD_GPIOD15_SANTIAGO,
	PAD_GPIOD16_SANTIAGO, PAD_GPIOD17_SANTIAGO, PAD_GPIOD18_SANTIAGO, PAD_GPIOD19_SANTIAGO,
	PAD_GPIOD20_SANTIAGO, PAD_GPIOD21_SANTIAGO, PAD_GPIOD22_SANTIAGO, PAD_GPIOD23_SANTIAGO,
	PAD_GPIOD24_SANTIAGO, PAD_GPIOD25_SANTIAGO, PAD_GPIOD26_SANTIAGO, PAD_GPIOD27_SANTIAGO,
	PAD_GPIOD28_SANTIAGO, PAD_GPIOD29_SANTIAGO, PAD_GPIOD30_SANTIAGO, PAD_GPIOD31_SANTIAGO,
	},
	/* GPIO group E */
	{
	PAD_GPIOE00_SANTIAGO, PAD_GPIOE01_SANTIAGO, PAD_GPIOE02_SANTIAGO, PAD_GPIOE03_SANTIAGO,
	PAD_GPIOE04_SANTIAGO, PAD_GPIOE05_SANTIAGO, PAD_GPIOE06_SANTIAGO, PAD_GPIOE07_SANTIAGO,
	PAD_GPIOE08_SANTIAGO, PAD_GPIOE09_SANTIAGO, PAD_GPIOE10_SANTIAGO, PAD_GPIOE11_SANTIAGO,
	PAD_GPIOE12_SANTIAGO, PAD_GPIOE13_SANTIAGO, PAD_GPIOE14_SANTIAGO, PAD_GPIOE15_SANTIAGO,
	PAD_GPIOE16_SANTIAGO, PAD_GPIOE17_SANTIAGO, PAD_GPIOE18_SANTIAGO, PAD_GPIOE19_SANTIAGO,
	PAD_GPIOE20_SANTIAGO, PAD_GPIOE21_SANTIAGO, PAD_GPIOE22_SANTIAGO, PAD_GPIOE23_SANTIAGO,
	PAD_GPIOE24_SANTIAGO, PAD_GPIOE25_SANTIAGO, PAD_GPIOE26_SANTIAGO, PAD_GPIOE27_SANTIAGO,
	PAD_GPIOE28_SANTIAGO, PAD_GPIOE29_SANTIAGO, PAD_GPIOE30_SANTIAGO, PAD_GPIOE31_SANTIAGO,
	},
};

const U32 alv_pad_santiago[6] = {
	PAD_GPIOALV00_SANTIAGO, PAD_GPIOALV01_SANTIAGO, PAD_GPIOALV02_SANTIAGO, PAD_GPIOALV03_SANTIAGO,
	PAD_GPIOALV04_SANTIAGO, PAD_GPIOALV05_SANTIAGO, 	};

const U32 bus_pad_santiago[6] = {
	PAD_BUS_STATIC_CNTL_SANTIAGO, PAD_BUS_STATIC_ADDR_SANTIAGO, PAD_BUS_STATIC_DATA_SANTIAGO,
	PAD_BUS_VSYNC_SANTIAGO, PAD_BUS_HSYNC_SANTIAGO, PAD_BUS_DE_SANTIAGO
};
