#
# Copyright 2009 Nexell Co.
#
# Makefile for the NXP4330

obj-y				  := test.o
#obj-y				  := board.o #device.o flash.o
#obj-$(CONFIG_ION_NXP) += dev-ion.o
#obj-$(CONFIG_KEYBOARD_GPIO) +=  keyboard.o
