################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../drivers/media/video/built-in.o 

C_SRCS += \
../drivers/media/video/adp1653.c \
../drivers/media/video/adv7170.c \
../drivers/media/video/adv7175.c \
../drivers/media/video/adv7180.c \
../drivers/media/video/adv7183.c \
../drivers/media/video/adv7343.c \
../drivers/media/video/ak881x.c \
../drivers/media/video/aptina-pll.c \
../drivers/media/video/arv.c \
../drivers/media/video/as3645a.c \
../drivers/media/video/atmel-isi.c \
../drivers/media/video/bt819.c \
../drivers/media/video/bt856.c \
../drivers/media/video/bt866.c \
../drivers/media/video/btcx-risc.c \
../drivers/media/video/bw-qcam.c \
../drivers/media/video/c-qcam.c \
../drivers/media/video/cs5345.c \
../drivers/media/video/cs53l32a.c \
../drivers/media/video/cx2341x.c \
../drivers/media/video/fsl-viu.c \
../drivers/media/video/hexium_gemini.c \
../drivers/media/video/hexium_orion.c \
../drivers/media/video/imx074.c \
../drivers/media/video/indycam.c \
../drivers/media/video/ir-kbd-i2c.c \
../drivers/media/video/ks0127.c \
../drivers/media/video/m52790.c \
../drivers/media/video/mem2mem_testdev.c \
../drivers/media/video/meye.c \
../drivers/media/video/msp3400-driver.c \
../drivers/media/video/msp3400-kthreads.c \
../drivers/media/video/mt9m001.c \
../drivers/media/video/mt9m032.c \
../drivers/media/video/mt9m111.c \
../drivers/media/video/mt9p031.c \
../drivers/media/video/mt9t001.c \
../drivers/media/video/mt9t031.c \
../drivers/media/video/mt9t112.c \
../drivers/media/video/mt9v011.c \
../drivers/media/video/mt9v022.c \
../drivers/media/video/mt9v032.c \
../drivers/media/video/mx1_camera.c \
../drivers/media/video/mx2_camera.c \
../drivers/media/video/mx2_emmaprp.c \
../drivers/media/video/mx3_camera.c \
../drivers/media/video/mxb.c \
../drivers/media/video/noon010pc30.c \
../drivers/media/video/omap1_camera.c \
../drivers/media/video/omap24xxcam-dma.c \
../drivers/media/video/omap24xxcam.c \
../drivers/media/video/ov2640.c \
../drivers/media/video/ov5642.c \
../drivers/media/video/ov6650.c \
../drivers/media/video/ov7670.c \
../drivers/media/video/ov772x.c \
../drivers/media/video/ov9640.c \
../drivers/media/video/ov9740.c \
../drivers/media/video/pms.c \
../drivers/media/video/pxa_camera.c \
../drivers/media/video/rj54n1cb0c.c \
../drivers/media/video/s2255drv.c \
../drivers/media/video/s5k5cagx.c \
../drivers/media/video/s5k6aa.c \
../drivers/media/video/saa6588.c \
../drivers/media/video/saa7110.c \
../drivers/media/video/saa7115.c \
../drivers/media/video/saa7127.c \
../drivers/media/video/saa717x.c \
../drivers/media/video/saa7185.c \
../drivers/media/video/saa7191.c \
../drivers/media/video/sh_mobile_ceu_camera.c \
../drivers/media/video/sh_mobile_csi2.c \
../drivers/media/video/sh_vou.c \
../drivers/media/video/soc_camera.c \
../drivers/media/video/soc_camera_platform.c \
../drivers/media/video/soc_mediabus.c \
../drivers/media/video/sr030pc30.c \
../drivers/media/video/stk-sensor.c \
../drivers/media/video/stk-webcam.c \
../drivers/media/video/tcm825x.c \
../drivers/media/video/tda7432.c \
../drivers/media/video/tda9840.c \
../drivers/media/video/tea6415c.c \
../drivers/media/video/tea6420.c \
../drivers/media/video/ths7303.c \
../drivers/media/video/timblogiw.c \
../drivers/media/video/tlv320aic23b.c \
../drivers/media/video/tuner-core.c \
../drivers/media/video/tvaudio.c \
../drivers/media/video/tveeprom.c \
../drivers/media/video/tvp514x.c \
../drivers/media/video/tvp5150.c \
../drivers/media/video/tvp7002.c \
../drivers/media/video/tw9910.c \
../drivers/media/video/upd64031a.c \
../drivers/media/video/upd64083.c \
../drivers/media/video/v4l2-common.c \
../drivers/media/video/v4l2-compat-ioctl32.c \
../drivers/media/video/v4l2-ctrls.c \
../drivers/media/video/v4l2-dev.c \
../drivers/media/video/v4l2-device.c \
../drivers/media/video/v4l2-event.c \
../drivers/media/video/v4l2-fh.c \
../drivers/media/video/v4l2-int-device.c \
../drivers/media/video/v4l2-ioctl.c \
../drivers/media/video/v4l2-mem2mem.c \
../drivers/media/video/v4l2-subdev.c \
../drivers/media/video/via-camera.c \
../drivers/media/video/videobuf-core.c \
../drivers/media/video/videobuf-dma-contig.c \
../drivers/media/video/videobuf-dma-sg.c \
../drivers/media/video/videobuf-dvb.c \
../drivers/media/video/videobuf-vmalloc.c \
../drivers/media/video/videobuf2-cma-phys.c \
../drivers/media/video/videobuf2-core.c \
../drivers/media/video/videobuf2-dma-contig.c \
../drivers/media/video/videobuf2-dma-sg.c \
../drivers/media/video/videobuf2-ion-nxp.c \
../drivers/media/video/videobuf2-ion.c \
../drivers/media/video/videobuf2-memops.c \
../drivers/media/video/videobuf2-vmalloc.c \
../drivers/media/video/vino.c \
../drivers/media/video/vivi.c \
../drivers/media/video/vp27smpx.c \
../drivers/media/video/vpx3220.c \
../drivers/media/video/vs6624.c \
../drivers/media/video/w9966.c \
../drivers/media/video/wm8739.c \
../drivers/media/video/wm8775.c \
../drivers/media/video/zr364xx.c 

OBJS += \
./drivers/media/video/adp1653.o \
./drivers/media/video/adv7170.o \
./drivers/media/video/adv7175.o \
./drivers/media/video/adv7180.o \
./drivers/media/video/adv7183.o \
./drivers/media/video/adv7343.o \
./drivers/media/video/ak881x.o \
./drivers/media/video/aptina-pll.o \
./drivers/media/video/arv.o \
./drivers/media/video/as3645a.o \
./drivers/media/video/atmel-isi.o \
./drivers/media/video/bt819.o \
./drivers/media/video/bt856.o \
./drivers/media/video/bt866.o \
./drivers/media/video/btcx-risc.o \
./drivers/media/video/bw-qcam.o \
./drivers/media/video/c-qcam.o \
./drivers/media/video/cs5345.o \
./drivers/media/video/cs53l32a.o \
./drivers/media/video/cx2341x.o \
./drivers/media/video/fsl-viu.o \
./drivers/media/video/hexium_gemini.o \
./drivers/media/video/hexium_orion.o \
./drivers/media/video/imx074.o \
./drivers/media/video/indycam.o \
./drivers/media/video/ir-kbd-i2c.o \
./drivers/media/video/ks0127.o \
./drivers/media/video/m52790.o \
./drivers/media/video/mem2mem_testdev.o \
./drivers/media/video/meye.o \
./drivers/media/video/msp3400-driver.o \
./drivers/media/video/msp3400-kthreads.o \
./drivers/media/video/mt9m001.o \
./drivers/media/video/mt9m032.o \
./drivers/media/video/mt9m111.o \
./drivers/media/video/mt9p031.o \
./drivers/media/video/mt9t001.o \
./drivers/media/video/mt9t031.o \
./drivers/media/video/mt9t112.o \
./drivers/media/video/mt9v011.o \
./drivers/media/video/mt9v022.o \
./drivers/media/video/mt9v032.o \
./drivers/media/video/mx1_camera.o \
./drivers/media/video/mx2_camera.o \
./drivers/media/video/mx2_emmaprp.o \
./drivers/media/video/mx3_camera.o \
./drivers/media/video/mxb.o \
./drivers/media/video/noon010pc30.o \
./drivers/media/video/omap1_camera.o \
./drivers/media/video/omap24xxcam-dma.o \
./drivers/media/video/omap24xxcam.o \
./drivers/media/video/ov2640.o \
./drivers/media/video/ov5642.o \
./drivers/media/video/ov6650.o \
./drivers/media/video/ov7670.o \
./drivers/media/video/ov772x.o \
./drivers/media/video/ov9640.o \
./drivers/media/video/ov9740.o \
./drivers/media/video/pms.o \
./drivers/media/video/pxa_camera.o \
./drivers/media/video/rj54n1cb0c.o \
./drivers/media/video/s2255drv.o \
./drivers/media/video/s5k5cagx.o \
./drivers/media/video/s5k6aa.o \
./drivers/media/video/saa6588.o \
./drivers/media/video/saa7110.o \
./drivers/media/video/saa7115.o \
./drivers/media/video/saa7127.o \
./drivers/media/video/saa717x.o \
./drivers/media/video/saa7185.o \
./drivers/media/video/saa7191.o \
./drivers/media/video/sh_mobile_ceu_camera.o \
./drivers/media/video/sh_mobile_csi2.o \
./drivers/media/video/sh_vou.o \
./drivers/media/video/soc_camera.o \
./drivers/media/video/soc_camera_platform.o \
./drivers/media/video/soc_mediabus.o \
./drivers/media/video/sr030pc30.o \
./drivers/media/video/stk-sensor.o \
./drivers/media/video/stk-webcam.o \
./drivers/media/video/tcm825x.o \
./drivers/media/video/tda7432.o \
./drivers/media/video/tda9840.o \
./drivers/media/video/tea6415c.o \
./drivers/media/video/tea6420.o \
./drivers/media/video/ths7303.o \
./drivers/media/video/timblogiw.o \
./drivers/media/video/tlv320aic23b.o \
./drivers/media/video/tuner-core.o \
./drivers/media/video/tvaudio.o \
./drivers/media/video/tveeprom.o \
./drivers/media/video/tvp514x.o \
./drivers/media/video/tvp5150.o \
./drivers/media/video/tvp7002.o \
./drivers/media/video/tw9910.o \
./drivers/media/video/upd64031a.o \
./drivers/media/video/upd64083.o \
./drivers/media/video/v4l2-common.o \
./drivers/media/video/v4l2-compat-ioctl32.o \
./drivers/media/video/v4l2-ctrls.o \
./drivers/media/video/v4l2-dev.o \
./drivers/media/video/v4l2-device.o \
./drivers/media/video/v4l2-event.o \
./drivers/media/video/v4l2-fh.o \
./drivers/media/video/v4l2-int-device.o \
./drivers/media/video/v4l2-ioctl.o \
./drivers/media/video/v4l2-mem2mem.o \
./drivers/media/video/v4l2-subdev.o \
./drivers/media/video/via-camera.o \
./drivers/media/video/videobuf-core.o \
./drivers/media/video/videobuf-dma-contig.o \
./drivers/media/video/videobuf-dma-sg.o \
./drivers/media/video/videobuf-dvb.o \
./drivers/media/video/videobuf-vmalloc.o \
./drivers/media/video/videobuf2-cma-phys.o \
./drivers/media/video/videobuf2-core.o \
./drivers/media/video/videobuf2-dma-contig.o \
./drivers/media/video/videobuf2-dma-sg.o \
./drivers/media/video/videobuf2-ion-nxp.o \
./drivers/media/video/videobuf2-ion.o \
./drivers/media/video/videobuf2-memops.o \
./drivers/media/video/videobuf2-vmalloc.o \
./drivers/media/video/vino.o \
./drivers/media/video/vivi.o \
./drivers/media/video/vp27smpx.o \
./drivers/media/video/vpx3220.o \
./drivers/media/video/vs6624.o \
./drivers/media/video/w9966.o \
./drivers/media/video/wm8739.o \
./drivers/media/video/wm8775.o \
./drivers/media/video/zr364xx.o 

C_DEPS += \
./drivers/media/video/adp1653.d \
./drivers/media/video/adv7170.d \
./drivers/media/video/adv7175.d \
./drivers/media/video/adv7180.d \
./drivers/media/video/adv7183.d \
./drivers/media/video/adv7343.d \
./drivers/media/video/ak881x.d \
./drivers/media/video/aptina-pll.d \
./drivers/media/video/arv.d \
./drivers/media/video/as3645a.d \
./drivers/media/video/atmel-isi.d \
./drivers/media/video/bt819.d \
./drivers/media/video/bt856.d \
./drivers/media/video/bt866.d \
./drivers/media/video/btcx-risc.d \
./drivers/media/video/bw-qcam.d \
./drivers/media/video/c-qcam.d \
./drivers/media/video/cs5345.d \
./drivers/media/video/cs53l32a.d \
./drivers/media/video/cx2341x.d \
./drivers/media/video/fsl-viu.d \
./drivers/media/video/hexium_gemini.d \
./drivers/media/video/hexium_orion.d \
./drivers/media/video/imx074.d \
./drivers/media/video/indycam.d \
./drivers/media/video/ir-kbd-i2c.d \
./drivers/media/video/ks0127.d \
./drivers/media/video/m52790.d \
./drivers/media/video/mem2mem_testdev.d \
./drivers/media/video/meye.d \
./drivers/media/video/msp3400-driver.d \
./drivers/media/video/msp3400-kthreads.d \
./drivers/media/video/mt9m001.d \
./drivers/media/video/mt9m032.d \
./drivers/media/video/mt9m111.d \
./drivers/media/video/mt9p031.d \
./drivers/media/video/mt9t001.d \
./drivers/media/video/mt9t031.d \
./drivers/media/video/mt9t112.d \
./drivers/media/video/mt9v011.d \
./drivers/media/video/mt9v022.d \
./drivers/media/video/mt9v032.d \
./drivers/media/video/mx1_camera.d \
./drivers/media/video/mx2_camera.d \
./drivers/media/video/mx2_emmaprp.d \
./drivers/media/video/mx3_camera.d \
./drivers/media/video/mxb.d \
./drivers/media/video/noon010pc30.d \
./drivers/media/video/omap1_camera.d \
./drivers/media/video/omap24xxcam-dma.d \
./drivers/media/video/omap24xxcam.d \
./drivers/media/video/ov2640.d \
./drivers/media/video/ov5642.d \
./drivers/media/video/ov6650.d \
./drivers/media/video/ov7670.d \
./drivers/media/video/ov772x.d \
./drivers/media/video/ov9640.d \
./drivers/media/video/ov9740.d \
./drivers/media/video/pms.d \
./drivers/media/video/pxa_camera.d \
./drivers/media/video/rj54n1cb0c.d \
./drivers/media/video/s2255drv.d \
./drivers/media/video/s5k5cagx.d \
./drivers/media/video/s5k6aa.d \
./drivers/media/video/saa6588.d \
./drivers/media/video/saa7110.d \
./drivers/media/video/saa7115.d \
./drivers/media/video/saa7127.d \
./drivers/media/video/saa717x.d \
./drivers/media/video/saa7185.d \
./drivers/media/video/saa7191.d \
./drivers/media/video/sh_mobile_ceu_camera.d \
./drivers/media/video/sh_mobile_csi2.d \
./drivers/media/video/sh_vou.d \
./drivers/media/video/soc_camera.d \
./drivers/media/video/soc_camera_platform.d \
./drivers/media/video/soc_mediabus.d \
./drivers/media/video/sr030pc30.d \
./drivers/media/video/stk-sensor.d \
./drivers/media/video/stk-webcam.d \
./drivers/media/video/tcm825x.d \
./drivers/media/video/tda7432.d \
./drivers/media/video/tda9840.d \
./drivers/media/video/tea6415c.d \
./drivers/media/video/tea6420.d \
./drivers/media/video/ths7303.d \
./drivers/media/video/timblogiw.d \
./drivers/media/video/tlv320aic23b.d \
./drivers/media/video/tuner-core.d \
./drivers/media/video/tvaudio.d \
./drivers/media/video/tveeprom.d \
./drivers/media/video/tvp514x.d \
./drivers/media/video/tvp5150.d \
./drivers/media/video/tvp7002.d \
./drivers/media/video/tw9910.d \
./drivers/media/video/upd64031a.d \
./drivers/media/video/upd64083.d \
./drivers/media/video/v4l2-common.d \
./drivers/media/video/v4l2-compat-ioctl32.d \
./drivers/media/video/v4l2-ctrls.d \
./drivers/media/video/v4l2-dev.d \
./drivers/media/video/v4l2-device.d \
./drivers/media/video/v4l2-event.d \
./drivers/media/video/v4l2-fh.d \
./drivers/media/video/v4l2-int-device.d \
./drivers/media/video/v4l2-ioctl.d \
./drivers/media/video/v4l2-mem2mem.d \
./drivers/media/video/v4l2-subdev.d \
./drivers/media/video/via-camera.d \
./drivers/media/video/videobuf-core.d \
./drivers/media/video/videobuf-dma-contig.d \
./drivers/media/video/videobuf-dma-sg.d \
./drivers/media/video/videobuf-dvb.d \
./drivers/media/video/videobuf-vmalloc.d \
./drivers/media/video/videobuf2-cma-phys.d \
./drivers/media/video/videobuf2-core.d \
./drivers/media/video/videobuf2-dma-contig.d \
./drivers/media/video/videobuf2-dma-sg.d \
./drivers/media/video/videobuf2-ion-nxp.d \
./drivers/media/video/videobuf2-ion.d \
./drivers/media/video/videobuf2-memops.d \
./drivers/media/video/videobuf2-vmalloc.d \
./drivers/media/video/vino.d \
./drivers/media/video/vivi.d \
./drivers/media/video/vp27smpx.d \
./drivers/media/video/vpx3220.d \
./drivers/media/video/vs6624.d \
./drivers/media/video/w9966.d \
./drivers/media/video/wm8739.d \
./drivers/media/video/wm8775.d \
./drivers/media/video/zr364xx.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/media/video/%.o: ../drivers/media/video/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


