################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../drivers/ata/acard-ahci.c \
../drivers/ata/ahci.c \
../drivers/ata/ahci_platform.c \
../drivers/ata/ata_generic.c \
../drivers/ata/ata_piix.c \
../drivers/ata/libahci.c \
../drivers/ata/libata-acpi.c \
../drivers/ata/libata-core.c \
../drivers/ata/libata-eh.c \
../drivers/ata/libata-pmp.c \
../drivers/ata/libata-scsi.c \
../drivers/ata/libata-sff.c \
../drivers/ata/libata-transport.c \
../drivers/ata/pata_acpi.c \
../drivers/ata/pata_ali.c \
../drivers/ata/pata_amd.c \
../drivers/ata/pata_arasan_cf.c \
../drivers/ata/pata_artop.c \
../drivers/ata/pata_at32.c \
../drivers/ata/pata_at91.c \
../drivers/ata/pata_atiixp.c \
../drivers/ata/pata_atp867x.c \
../drivers/ata/pata_bf54x.c \
../drivers/ata/pata_cmd640.c \
../drivers/ata/pata_cmd64x.c \
../drivers/ata/pata_cs5520.c \
../drivers/ata/pata_cs5530.c \
../drivers/ata/pata_cs5535.c \
../drivers/ata/pata_cs5536.c \
../drivers/ata/pata_cypress.c \
../drivers/ata/pata_efar.c \
../drivers/ata/pata_hpt366.c \
../drivers/ata/pata_hpt37x.c \
../drivers/ata/pata_hpt3x2n.c \
../drivers/ata/pata_hpt3x3.c \
../drivers/ata/pata_icside.c \
../drivers/ata/pata_imx.c \
../drivers/ata/pata_isapnp.c \
../drivers/ata/pata_it8213.c \
../drivers/ata/pata_it821x.c \
../drivers/ata/pata_ixp4xx_cf.c \
../drivers/ata/pata_jmicron.c \
../drivers/ata/pata_legacy.c \
../drivers/ata/pata_macio.c \
../drivers/ata/pata_marvell.c \
../drivers/ata/pata_mpc52xx.c \
../drivers/ata/pata_mpiix.c \
../drivers/ata/pata_netcell.c \
../drivers/ata/pata_ninja32.c \
../drivers/ata/pata_ns87410.c \
../drivers/ata/pata_ns87415.c \
../drivers/ata/pata_octeon_cf.c \
../drivers/ata/pata_of_platform.c \
../drivers/ata/pata_oldpiix.c \
../drivers/ata/pata_opti.c \
../drivers/ata/pata_optidma.c \
../drivers/ata/pata_palmld.c \
../drivers/ata/pata_pcmcia.c \
../drivers/ata/pata_pdc2027x.c \
../drivers/ata/pata_pdc202xx_old.c \
../drivers/ata/pata_piccolo.c \
../drivers/ata/pata_platform.c \
../drivers/ata/pata_pxa.c \
../drivers/ata/pata_radisys.c \
../drivers/ata/pata_rb532_cf.c \
../drivers/ata/pata_rdc.c \
../drivers/ata/pata_rz1000.c \
../drivers/ata/pata_samsung_cf.c \
../drivers/ata/pata_sc1200.c \
../drivers/ata/pata_scc.c \
../drivers/ata/pata_sch.c \
../drivers/ata/pata_serverworks.c \
../drivers/ata/pata_sil680.c \
../drivers/ata/pata_sis.c \
../drivers/ata/pata_sl82c105.c \
../drivers/ata/pata_triflex.c \
../drivers/ata/pata_via.c \
../drivers/ata/pdc_adma.c \
../drivers/ata/sata_dwc_460ex.c \
../drivers/ata/sata_fsl.c \
../drivers/ata/sata_inic162x.c \
../drivers/ata/sata_mv.c \
../drivers/ata/sata_nv.c \
../drivers/ata/sata_promise.c \
../drivers/ata/sata_qstor.c \
../drivers/ata/sata_sil.c \
../drivers/ata/sata_sil24.c \
../drivers/ata/sata_sis.c \
../drivers/ata/sata_svw.c \
../drivers/ata/sata_sx4.c \
../drivers/ata/sata_uli.c \
../drivers/ata/sata_via.c \
../drivers/ata/sata_vsc.c 

OBJS += \
./drivers/ata/acard-ahci.o \
./drivers/ata/ahci.o \
./drivers/ata/ahci_platform.o \
./drivers/ata/ata_generic.o \
./drivers/ata/ata_piix.o \
./drivers/ata/libahci.o \
./drivers/ata/libata-acpi.o \
./drivers/ata/libata-core.o \
./drivers/ata/libata-eh.o \
./drivers/ata/libata-pmp.o \
./drivers/ata/libata-scsi.o \
./drivers/ata/libata-sff.o \
./drivers/ata/libata-transport.o \
./drivers/ata/pata_acpi.o \
./drivers/ata/pata_ali.o \
./drivers/ata/pata_amd.o \
./drivers/ata/pata_arasan_cf.o \
./drivers/ata/pata_artop.o \
./drivers/ata/pata_at32.o \
./drivers/ata/pata_at91.o \
./drivers/ata/pata_atiixp.o \
./drivers/ata/pata_atp867x.o \
./drivers/ata/pata_bf54x.o \
./drivers/ata/pata_cmd640.o \
./drivers/ata/pata_cmd64x.o \
./drivers/ata/pata_cs5520.o \
./drivers/ata/pata_cs5530.o \
./drivers/ata/pata_cs5535.o \
./drivers/ata/pata_cs5536.o \
./drivers/ata/pata_cypress.o \
./drivers/ata/pata_efar.o \
./drivers/ata/pata_hpt366.o \
./drivers/ata/pata_hpt37x.o \
./drivers/ata/pata_hpt3x2n.o \
./drivers/ata/pata_hpt3x3.o \
./drivers/ata/pata_icside.o \
./drivers/ata/pata_imx.o \
./drivers/ata/pata_isapnp.o \
./drivers/ata/pata_it8213.o \
./drivers/ata/pata_it821x.o \
./drivers/ata/pata_ixp4xx_cf.o \
./drivers/ata/pata_jmicron.o \
./drivers/ata/pata_legacy.o \
./drivers/ata/pata_macio.o \
./drivers/ata/pata_marvell.o \
./drivers/ata/pata_mpc52xx.o \
./drivers/ata/pata_mpiix.o \
./drivers/ata/pata_netcell.o \
./drivers/ata/pata_ninja32.o \
./drivers/ata/pata_ns87410.o \
./drivers/ata/pata_ns87415.o \
./drivers/ata/pata_octeon_cf.o \
./drivers/ata/pata_of_platform.o \
./drivers/ata/pata_oldpiix.o \
./drivers/ata/pata_opti.o \
./drivers/ata/pata_optidma.o \
./drivers/ata/pata_palmld.o \
./drivers/ata/pata_pcmcia.o \
./drivers/ata/pata_pdc2027x.o \
./drivers/ata/pata_pdc202xx_old.o \
./drivers/ata/pata_piccolo.o \
./drivers/ata/pata_platform.o \
./drivers/ata/pata_pxa.o \
./drivers/ata/pata_radisys.o \
./drivers/ata/pata_rb532_cf.o \
./drivers/ata/pata_rdc.o \
./drivers/ata/pata_rz1000.o \
./drivers/ata/pata_samsung_cf.o \
./drivers/ata/pata_sc1200.o \
./drivers/ata/pata_scc.o \
./drivers/ata/pata_sch.o \
./drivers/ata/pata_serverworks.o \
./drivers/ata/pata_sil680.o \
./drivers/ata/pata_sis.o \
./drivers/ata/pata_sl82c105.o \
./drivers/ata/pata_triflex.o \
./drivers/ata/pata_via.o \
./drivers/ata/pdc_adma.o \
./drivers/ata/sata_dwc_460ex.o \
./drivers/ata/sata_fsl.o \
./drivers/ata/sata_inic162x.o \
./drivers/ata/sata_mv.o \
./drivers/ata/sata_nv.o \
./drivers/ata/sata_promise.o \
./drivers/ata/sata_qstor.o \
./drivers/ata/sata_sil.o \
./drivers/ata/sata_sil24.o \
./drivers/ata/sata_sis.o \
./drivers/ata/sata_svw.o \
./drivers/ata/sata_sx4.o \
./drivers/ata/sata_uli.o \
./drivers/ata/sata_via.o \
./drivers/ata/sata_vsc.o 

C_DEPS += \
./drivers/ata/acard-ahci.d \
./drivers/ata/ahci.d \
./drivers/ata/ahci_platform.d \
./drivers/ata/ata_generic.d \
./drivers/ata/ata_piix.d \
./drivers/ata/libahci.d \
./drivers/ata/libata-acpi.d \
./drivers/ata/libata-core.d \
./drivers/ata/libata-eh.d \
./drivers/ata/libata-pmp.d \
./drivers/ata/libata-scsi.d \
./drivers/ata/libata-sff.d \
./drivers/ata/libata-transport.d \
./drivers/ata/pata_acpi.d \
./drivers/ata/pata_ali.d \
./drivers/ata/pata_amd.d \
./drivers/ata/pata_arasan_cf.d \
./drivers/ata/pata_artop.d \
./drivers/ata/pata_at32.d \
./drivers/ata/pata_at91.d \
./drivers/ata/pata_atiixp.d \
./drivers/ata/pata_atp867x.d \
./drivers/ata/pata_bf54x.d \
./drivers/ata/pata_cmd640.d \
./drivers/ata/pata_cmd64x.d \
./drivers/ata/pata_cs5520.d \
./drivers/ata/pata_cs5530.d \
./drivers/ata/pata_cs5535.d \
./drivers/ata/pata_cs5536.d \
./drivers/ata/pata_cypress.d \
./drivers/ata/pata_efar.d \
./drivers/ata/pata_hpt366.d \
./drivers/ata/pata_hpt37x.d \
./drivers/ata/pata_hpt3x2n.d \
./drivers/ata/pata_hpt3x3.d \
./drivers/ata/pata_icside.d \
./drivers/ata/pata_imx.d \
./drivers/ata/pata_isapnp.d \
./drivers/ata/pata_it8213.d \
./drivers/ata/pata_it821x.d \
./drivers/ata/pata_ixp4xx_cf.d \
./drivers/ata/pata_jmicron.d \
./drivers/ata/pata_legacy.d \
./drivers/ata/pata_macio.d \
./drivers/ata/pata_marvell.d \
./drivers/ata/pata_mpc52xx.d \
./drivers/ata/pata_mpiix.d \
./drivers/ata/pata_netcell.d \
./drivers/ata/pata_ninja32.d \
./drivers/ata/pata_ns87410.d \
./drivers/ata/pata_ns87415.d \
./drivers/ata/pata_octeon_cf.d \
./drivers/ata/pata_of_platform.d \
./drivers/ata/pata_oldpiix.d \
./drivers/ata/pata_opti.d \
./drivers/ata/pata_optidma.d \
./drivers/ata/pata_palmld.d \
./drivers/ata/pata_pcmcia.d \
./drivers/ata/pata_pdc2027x.d \
./drivers/ata/pata_pdc202xx_old.d \
./drivers/ata/pata_piccolo.d \
./drivers/ata/pata_platform.d \
./drivers/ata/pata_pxa.d \
./drivers/ata/pata_radisys.d \
./drivers/ata/pata_rb532_cf.d \
./drivers/ata/pata_rdc.d \
./drivers/ata/pata_rz1000.d \
./drivers/ata/pata_samsung_cf.d \
./drivers/ata/pata_sc1200.d \
./drivers/ata/pata_scc.d \
./drivers/ata/pata_sch.d \
./drivers/ata/pata_serverworks.d \
./drivers/ata/pata_sil680.d \
./drivers/ata/pata_sis.d \
./drivers/ata/pata_sl82c105.d \
./drivers/ata/pata_triflex.d \
./drivers/ata/pata_via.d \
./drivers/ata/pdc_adma.d \
./drivers/ata/sata_dwc_460ex.d \
./drivers/ata/sata_fsl.d \
./drivers/ata/sata_inic162x.d \
./drivers/ata/sata_mv.d \
./drivers/ata/sata_nv.d \
./drivers/ata/sata_promise.d \
./drivers/ata/sata_qstor.d \
./drivers/ata/sata_sil.d \
./drivers/ata/sata_sil24.d \
./drivers/ata/sata_sis.d \
./drivers/ata/sata_svw.d \
./drivers/ata/sata_sx4.d \
./drivers/ata/sata_uli.d \
./drivers/ata/sata_via.d \
./drivers/ata/sata_vsc.d 


# Each subdirectory must supply rules for building sources it contributes
drivers/ata/%.o: ../drivers/ata/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


