#
# Copyright 2009 Nexell Co.
#
# Makefile for the NNXP CPU

obj-y += rsc.o gpio.o
obj-$(CONFIG_ADC_NEXELL)			+= adc.o
obj-$(CONFIG_NEXELL_SOC_PWM)			+= pwm.o
obj-$(CONFIG_NEXELL_SOC_DISP)			+= display.o
obj-$(CONFIG_NEXELL_SOC_DISP_LVDS)		+= display_lvds.o
obj-$(CONFIG_NEXELL_SOC_DISP_HDMI)		+= display_hdmi.o hdmi-priv.o
obj-$(CONFIG_NEXELL_SOC_DISP_LCDIF)		+= display_lcdif.o
