################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
O_SRCS += \
../lib/argv_split.o \
../lib/audit.o \
../lib/average.o \
../lib/bcd.o \
../lib/bitmap.o \
../lib/bitrev.o \
../lib/bsearch.o \
../lib/bug.o \
../lib/built-in.o \
../lib/bust_spinlocks.o \
../lib/cmdline.o \
../lib/crc16.o \
../lib/crc32.o \
../lib/ctype.o \
../lib/debug_locks.o \
../lib/dec_and_lock.o \
../lib/decompress.o \
../lib/decompress_bunzip2.o \
../lib/decompress_inflate.o \
../lib/decompress_unlzma.o \
../lib/decompress_unlzo.o \
../lib/decompress_unxz.o \
../lib/devres.o \
../lib/div64.o \
../lib/dump_stack.o \
../lib/dynamic_queue_limits.o \
../lib/extable.o \
../lib/find_last_bit.o \
../lib/find_next_bit.o \
../lib/flex_array.o \
../lib/gcd.o \
../lib/halfmd4.o \
../lib/hexdump.o \
../lib/hweight.o \
../lib/idr.o \
../lib/int_sqrt.o \
../lib/iomap_copy.o \
../lib/ioremap.o \
../lib/irq_regs.o \
../lib/is_single_threaded.o \
../lib/kasprintf.o \
../lib/klist.o \
../lib/kobject.o \
../lib/kobject_uevent.o \
../lib/kstrtox.o \
../lib/lcm.o \
../lib/list_sort.o \
../lib/llist.o \
../lib/md5.o \
../lib/nlattr.o \
../lib/parser.o \
../lib/pci_iomap.o \
../lib/plist.o \
../lib/prio_heap.o \
../lib/prio_tree.o \
../lib/proportions.o \
../lib/radix-tree.o \
../lib/random32.o \
../lib/ratelimit.o \
../lib/rbtree.o \
../lib/reciprocal_div.o \
../lib/rwsem-spinlock.o \
../lib/scatterlist.o \
../lib/sha1.o \
../lib/show_mem.o \
../lib/smp_processor_id.o \
../lib/sort.o \
../lib/string.o \
../lib/string_helpers.o \
../lib/timerqueue.o \
../lib/uuid.o \
../lib/vsprintf.o 

C_SRCS += \
../lib/argv_split.c \
../lib/atomic64.c \
../lib/atomic64_test.c \
../lib/audit.c \
../lib/average.c \
../lib/bcd.c \
../lib/bch.c \
../lib/bitmap.c \
../lib/bitrev.c \
../lib/bsearch.c \
../lib/btree.c \
../lib/bug.c \
../lib/bust_spinlocks.c \
../lib/check_signature.c \
../lib/checksum.c \
../lib/clz_tab.c \
../lib/cmdline.c \
../lib/cordic.c \
../lib/cpu-notifier-error-inject.c \
../lib/cpu_rmap.c \
../lib/cpumask.c \
../lib/crc-ccitt.c \
../lib/crc-itu-t.c \
../lib/crc-t10dif.c \
../lib/crc16.c \
../lib/crc32.c \
../lib/crc7.c \
../lib/crc8.c \
../lib/ctype.c \
../lib/debug_locks.c \
../lib/debugobjects.c \
../lib/dec_and_lock.c \
../lib/decompress.c \
../lib/decompress_bunzip2.c \
../lib/decompress_inflate.c \
../lib/decompress_unlzma.c \
../lib/decompress_unlzo.c \
../lib/decompress_unxz.c \
../lib/devres.c \
../lib/digsig.c \
../lib/div64.c \
../lib/dma-debug.c \
../lib/dump_stack.c \
../lib/dynamic_debug.c \
../lib/dynamic_queue_limits.c \
../lib/extable.c \
../lib/fault-inject.c \
../lib/find_last_bit.c \
../lib/find_next_bit.c \
../lib/flex_array.c \
../lib/gcd.c \
../lib/gen_crc32table.c \
../lib/genalloc.c \
../lib/halfmd4.c \
../lib/hexdump.c \
../lib/hweight.c \
../lib/idr.c \
../lib/inflate.c \
../lib/int_sqrt.c \
../lib/iomap.c \
../lib/iomap_copy.c \
../lib/iommu-helper.c \
../lib/ioremap.c \
../lib/irq_regs.c \
../lib/is_single_threaded.c \
../lib/kasprintf.c \
../lib/klist.c \
../lib/kobject.c \
../lib/kobject_uevent.c \
../lib/kstrtox.c \
../lib/lcm.c \
../lib/libcrc32c.c \
../lib/list_debug.c \
../lib/list_sort.c \
../lib/llist.c \
../lib/locking-selftest.c \
../lib/lru_cache.c \
../lib/md5.c \
../lib/nlattr.c \
../lib/parser.c \
../lib/pci_iomap.c \
../lib/percpu_counter.c \
../lib/plist.c \
../lib/prio_heap.c \
../lib/prio_tree.c \
../lib/proportions.c \
../lib/radix-tree.c \
../lib/random32.c \
../lib/ratelimit.c \
../lib/rational.c \
../lib/rbtree.c \
../lib/reciprocal_div.c \
../lib/rwsem-spinlock.c \
../lib/rwsem.c \
../lib/scatterlist.c \
../lib/sha1.c \
../lib/show_mem.c \
../lib/smp_processor_id.c \
../lib/sort.c \
../lib/spinlock_debug.c \
../lib/string.c \
../lib/string_helpers.c \
../lib/swiotlb.c \
../lib/syscall.c \
../lib/test-kstrtox.c \
../lib/textsearch.c \
../lib/timerqueue.c \
../lib/ts_bm.c \
../lib/ts_fsm.c \
../lib/ts_kmp.c \
../lib/uuid.c \
../lib/vsprintf.c 

OBJS += \
./lib/argv_split.o \
./lib/atomic64.o \
./lib/atomic64_test.o \
./lib/audit.o \
./lib/average.o \
./lib/bcd.o \
./lib/bch.o \
./lib/bitmap.o \
./lib/bitrev.o \
./lib/bsearch.o \
./lib/btree.o \
./lib/bug.o \
./lib/bust_spinlocks.o \
./lib/check_signature.o \
./lib/checksum.o \
./lib/clz_tab.o \
./lib/cmdline.o \
./lib/cordic.o \
./lib/cpu-notifier-error-inject.o \
./lib/cpu_rmap.o \
./lib/cpumask.o \
./lib/crc-ccitt.o \
./lib/crc-itu-t.o \
./lib/crc-t10dif.o \
./lib/crc16.o \
./lib/crc32.o \
./lib/crc7.o \
./lib/crc8.o \
./lib/ctype.o \
./lib/debug_locks.o \
./lib/debugobjects.o \
./lib/dec_and_lock.o \
./lib/decompress.o \
./lib/decompress_bunzip2.o \
./lib/decompress_inflate.o \
./lib/decompress_unlzma.o \
./lib/decompress_unlzo.o \
./lib/decompress_unxz.o \
./lib/devres.o \
./lib/digsig.o \
./lib/div64.o \
./lib/dma-debug.o \
./lib/dump_stack.o \
./lib/dynamic_debug.o \
./lib/dynamic_queue_limits.o \
./lib/extable.o \
./lib/fault-inject.o \
./lib/find_last_bit.o \
./lib/find_next_bit.o \
./lib/flex_array.o \
./lib/gcd.o \
./lib/gen_crc32table.o \
./lib/genalloc.o \
./lib/halfmd4.o \
./lib/hexdump.o \
./lib/hweight.o \
./lib/idr.o \
./lib/inflate.o \
./lib/int_sqrt.o \
./lib/iomap.o \
./lib/iomap_copy.o \
./lib/iommu-helper.o \
./lib/ioremap.o \
./lib/irq_regs.o \
./lib/is_single_threaded.o \
./lib/kasprintf.o \
./lib/klist.o \
./lib/kobject.o \
./lib/kobject_uevent.o \
./lib/kstrtox.o \
./lib/lcm.o \
./lib/libcrc32c.o \
./lib/list_debug.o \
./lib/list_sort.o \
./lib/llist.o \
./lib/locking-selftest.o \
./lib/lru_cache.o \
./lib/md5.o \
./lib/nlattr.o \
./lib/parser.o \
./lib/pci_iomap.o \
./lib/percpu_counter.o \
./lib/plist.o \
./lib/prio_heap.o \
./lib/prio_tree.o \
./lib/proportions.o \
./lib/radix-tree.o \
./lib/random32.o \
./lib/ratelimit.o \
./lib/rational.o \
./lib/rbtree.o \
./lib/reciprocal_div.o \
./lib/rwsem-spinlock.o \
./lib/rwsem.o \
./lib/scatterlist.o \
./lib/sha1.o \
./lib/show_mem.o \
./lib/smp_processor_id.o \
./lib/sort.o \
./lib/spinlock_debug.o \
./lib/string.o \
./lib/string_helpers.o \
./lib/swiotlb.o \
./lib/syscall.o \
./lib/test-kstrtox.o \
./lib/textsearch.o \
./lib/timerqueue.o \
./lib/ts_bm.o \
./lib/ts_fsm.o \
./lib/ts_kmp.o \
./lib/uuid.o \
./lib/vsprintf.o 

C_DEPS += \
./lib/argv_split.d \
./lib/atomic64.d \
./lib/atomic64_test.d \
./lib/audit.d \
./lib/average.d \
./lib/bcd.d \
./lib/bch.d \
./lib/bitmap.d \
./lib/bitrev.d \
./lib/bsearch.d \
./lib/btree.d \
./lib/bug.d \
./lib/bust_spinlocks.d \
./lib/check_signature.d \
./lib/checksum.d \
./lib/clz_tab.d \
./lib/cmdline.d \
./lib/cordic.d \
./lib/cpu-notifier-error-inject.d \
./lib/cpu_rmap.d \
./lib/cpumask.d \
./lib/crc-ccitt.d \
./lib/crc-itu-t.d \
./lib/crc-t10dif.d \
./lib/crc16.d \
./lib/crc32.d \
./lib/crc7.d \
./lib/crc8.d \
./lib/ctype.d \
./lib/debug_locks.d \
./lib/debugobjects.d \
./lib/dec_and_lock.d \
./lib/decompress.d \
./lib/decompress_bunzip2.d \
./lib/decompress_inflate.d \
./lib/decompress_unlzma.d \
./lib/decompress_unlzo.d \
./lib/decompress_unxz.d \
./lib/devres.d \
./lib/digsig.d \
./lib/div64.d \
./lib/dma-debug.d \
./lib/dump_stack.d \
./lib/dynamic_debug.d \
./lib/dynamic_queue_limits.d \
./lib/extable.d \
./lib/fault-inject.d \
./lib/find_last_bit.d \
./lib/find_next_bit.d \
./lib/flex_array.d \
./lib/gcd.d \
./lib/gen_crc32table.d \
./lib/genalloc.d \
./lib/halfmd4.d \
./lib/hexdump.d \
./lib/hweight.d \
./lib/idr.d \
./lib/inflate.d \
./lib/int_sqrt.d \
./lib/iomap.d \
./lib/iomap_copy.d \
./lib/iommu-helper.d \
./lib/ioremap.d \
./lib/irq_regs.d \
./lib/is_single_threaded.d \
./lib/kasprintf.d \
./lib/klist.d \
./lib/kobject.d \
./lib/kobject_uevent.d \
./lib/kstrtox.d \
./lib/lcm.d \
./lib/libcrc32c.d \
./lib/list_debug.d \
./lib/list_sort.d \
./lib/llist.d \
./lib/locking-selftest.d \
./lib/lru_cache.d \
./lib/md5.d \
./lib/nlattr.d \
./lib/parser.d \
./lib/pci_iomap.d \
./lib/percpu_counter.d \
./lib/plist.d \
./lib/prio_heap.d \
./lib/prio_tree.d \
./lib/proportions.d \
./lib/radix-tree.d \
./lib/random32.d \
./lib/ratelimit.d \
./lib/rational.d \
./lib/rbtree.d \
./lib/reciprocal_div.d \
./lib/rwsem-spinlock.d \
./lib/rwsem.d \
./lib/scatterlist.d \
./lib/sha1.d \
./lib/show_mem.d \
./lib/smp_processor_id.d \
./lib/sort.d \
./lib/spinlock_debug.d \
./lib/string.d \
./lib/string_helpers.d \
./lib/swiotlb.d \
./lib/syscall.d \
./lib/test-kstrtox.d \
./lib/textsearch.d \
./lib/timerqueue.d \
./lib/ts_bm.d \
./lib/ts_fsm.d \
./lib/ts_kmp.d \
./lib/uuid.d \
./lib/vsprintf.d 


# Each subdirectory must supply rules for building sources it contributes
lib/%.o: ../lib/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: ARM Linux GCC C Compiler'
	arm-elf-gcc -O0 -Wall -Wa,-adhlns="$@.lst" -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@:%.o=%.d)" -mcpu=cortex-m4 -mthumb -g3 -gdwarf-2 -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


