#ifndef __CFG_GPIO_SANTIAGO_H__
#define __CFG_GPIO_SANTIAGO_H__

#include <mach/nxp4330.h>
/*------------------------------------------------------------------------------
*	GPIO Bank A
*/
#define PAD_GPIOA00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA01_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD0 */
#define PAD_GPIOA02_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD1 */
#define PAD_GPIOA03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD2 */
#define PAD_GPIOA04_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD3 */
#define PAD_GPIOA05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD4 */
#define PAD_GPIOA06_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD5 */
#define PAD_GPIOA07_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD6 */

#define PAD_GPIOA08_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PVD7 */
#define PAD_GPIOA09_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA10_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA11_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA12_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO
#define PAD_GPIOA13_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else	/* Bogota */
#define PAD_GPIOA13_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2S_SEL_BT */
#endif
#define PAD_GPIOA14_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOA15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: LVDS HSD */
#else
#define PAD_GPIOA15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#endif

#define PAD_GPIOA16_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOA17_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: CHG_GRN_DISABLE */
#else
#define PAD_GPIOA17_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#endif
#define PAD_GPIOA18_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA19_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA20_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA21_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA22_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA23_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */

#define PAD_GPIOA24_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA25_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA26_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOA27_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOUT_DE_R */
#define PAD_GPIOA28_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_PCLK */
#define PAD_GPIOA29_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK0_R */
#define PAD_GPIOA30_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_0 */
#define PAD_GPIOA31_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD0_R */
/*------------------------------------------------------------------------------
*	GPIO Bank B
*/
#define PAD_GPIOB00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_1 */
#define PAD_GPIOB01_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT00_R */
#define PAD_GPIOB02_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_2 */
#define PAD_GPIOB03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT01_R */
#define PAD_GPIOB04_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_3 */
#define PAD_GPIOB05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT02_R */
#define PAD_GPIOB06_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_4 */
#define PAD_GPIOB07_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT03_R */

#define PAD_GPIOB08_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_5 */
#define PAD_GPIOB09_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_6 */
#define PAD_GPIOB10_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_7 */
#define PAD_GPIOB11_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_CLE_R */
#define PAD_GPIOB12_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_ALE_R */
#define PAD_GPIOB13_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD0 */
#define PAD_GPIOB14_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_RNB */
#define PAD_GPIOB15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD1 */

#define PAD_GPIOB16_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFOE_R_L */
#define PAD_GPIOB17_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD2 */
#define PAD_GPIOB18_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NAND_NFWE_R_L */
#define PAD_GPIOB19_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD3 */
#define PAD_GPIOB20_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD4 */
#define PAD_GPIOB21_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD5 */
#define PAD_GPIOB22_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD6 */
#define PAD_GPIOB23_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SD7 */

#define PAD_GPIOB24_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_RST_RTP_Y2_R */
#define PAD_GPIOB25_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_INT_RTP_X2_R */
#define PAD_GPIOB26_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: MEM_VSEL */
#define PAD_GPIOB27_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB28_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOB29_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_UP_L */
#define PAD_GPIOB30_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VOL_DOWN_L */
#define PAD_GPIOB31_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
/*------------------------------------------------------------------------------
*	GPIO Bank C
*/
#define PAD_GPIOC00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC01_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CIP_L */
#define PAD_GPIOC02_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC04_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: PMIC_INT_L */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOC05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC06_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOC05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_HOST_CTS */
#define PAD_GPIOC06_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_HOST_RTS */
#endif
#define PAD_GPIOC07_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_RST_L */

#define PAD_GPIOC08_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: ACCEL_INT */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOC09_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOC09_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_RST_L */
#endif
#define PAD_GPIOC10_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: WIFI_WAKE */
#define PAD_GPIOC11_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOC12_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOC12_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_LINK */
#endif
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOC13_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LED Driver Enable/Dimming control */
#else
#define PAD_GPIOC13_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#endif
#define PAD_GPIOC14_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_RESET_L */
#define PAD_GPIOC15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_ENA_L FIXME: Output? */

#define PAD_GPIOC16_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_RESET_L */
#define PAD_GPIOC17_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: NC */
#define PAD_GPIOC18_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK2 */
#define PAD_GPIOC19_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD2 */
#define PAD_GPIOC20_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT20 */
#define PAD_GPIOC21_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT21 */
#define PAD_GPIOC22_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT22 */
#define PAD_GPIOC23_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT23 */

#define PAD_GPIOC24_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_ENA_L FIXME: Output? */
#define PAD_GPIOC25_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: nSWAIT */
#define PAD_GPIOC26_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC27_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC28_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOC29_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPCLK0_R */
#define PAD_GPIOC30_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPFRM0 */
#define PAD_GPIOC31_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPTXD0 */
/*------------------------------------------------------------------------------
*	GPIO Bank D
*/
#define PAD_GPIOD00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SSPRXD0 */
#define PAD_GPIOD01_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: MCU_PWM0 */
#define PAD_GPIOD02_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL0 */
#define PAD_GPIOD03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA0 */
#define PAD_GPIOD04_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCL1 */
#define PAD_GPIOD05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDA1 */
#define PAD_GPIOD06_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SDA_RTP_Y1_R */
#define PAD_GPIOD07_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: CTP_SCL_RTP_X1_R */

#define PAD_GPIOD08_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD09_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDOUT */
#define PAD_GPIOD10_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SBCLK */
#define PAD_GPIOD11_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SDIN */
#define PAD_GPIOD12_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SSYNC */
#define PAD_GPIOD13_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: I2SMCLK */
#define PAD_GPIOD14_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: RX0 */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOD15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOD15_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_HOST_RX */
#endif

#define PAD_GPIOD16_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD17_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD18_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: TX0 */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOD19_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOD19_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: BT_HOST_TX */
#endif
#define PAD_GPIOD20_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_DN | PAD_STRENGTH_2)		/* Pin Use: CHG_FLT */
#define PAD_GPIOD21_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOD22_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCLK1_R */
#define PAD_GPIOD23_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDCMD1_R */

#define PAD_GPIOD24_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT10_R */
#define PAD_GPIOD25_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT11_R */
#define PAD_GPIOD26_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT12_R */
#define PAD_GPIOD27_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDDAT13_R */
#define PAD_GPIOD28_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_0 */
#define PAD_GPIOD29_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_1 */
#define PAD_GPIOD30_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_2 */
#define PAD_GPIOD31_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_3 */
/*------------------------------------------------------------------------------
*	GPIO Bank E
*/
#define PAD_GPIOE00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_4 */
#define PAD_GPIOE01_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_5 */
#define PAD_GPIOE02_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_6 */
#define PAD_GPIOE03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_7 */
#define PAD_GPIOE04_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_PCLK */
#define PAD_GPIOE05_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_HSYNC */
#define PAD_GPIOE06_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID0_VSYNC */
#define PAD_GPIOE07_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_VSYNC */

#define PAD_GPIOE08_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE09_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_LEFT_L */
#define PAD_GPIOE10_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HP_DETECT */
#define PAD_GPIOE11_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE12_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: AUDIO_INT */
#define PAD_GPIOE13_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: VID1_HSYNC */
#define PAD_GPIOE14_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SCK */
#define PAD_GPIOE15_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_SCS_L */

#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should these be configured */
#define PAD_GPIOE16_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE17_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOE16_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: AUDIO_MUTE */
#define PAD_GPIOE17_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)	/* Pin Use: AUDIO_RST_L */
#endif
#define PAD_GPIOE18_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOE19_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT2 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: SDI */
#define PAD_GPIOE20_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: HOME_BTN_L */
#define PAD_GPIOE21_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_DN_L */
#ifdef CONFIG_PLAT_NXP4330_SANTIAGO	/* FIXME: How should this be configured */
#define PAD_GPIOE22_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#else
#define PAD_GPIOE22_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_HIGH | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: LCD_LED_ENA */
#endif
#define PAD_GPIOE23_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_RIGHT_L */

#define PAD_GPIOE24_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: DPAD_UP_L */
#define PAD_GPIOE25_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TRST_L */
#define PAD_GPIOE26_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TMS */
#define PAD_GPIOE27_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDI */
#define PAD_GPIOE28_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TCK */
#define PAD_GPIOE29_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: JTAG_TDO */
#define PAD_GPIOE30_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_OTG_ID */
#define PAD_GPIOE31_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT1 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_2)		/* Pin Use: USB_PWR_OK_L */
/*------------------------------------------------------------------------------
*	GPIO Bank ALV
*/
#define PAD_GPIOALV00_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP  | PAD_STRENGTH_0)		/* Pin Use: Power key */
#define PAD_GPIOALV01_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: NC */
#define PAD_GPIOALV02_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP  | PAD_STRENGTH_0)		/* Pin Use: MCU_VUSB_DET */
#define PAD_GPIOALV03_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP  | PAD_STRENGTH_0)		/* Pin Use: MCU_LOWBAT_DET */
#define PAD_GPIOALV04_SANTIAGO		(PAD_MODE_OUT | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_OFF | PAD_STRENGTH_0)		/* Pin Use: TP */
#define PAD_GPIOALV05_SANTIAGO		(PAD_MODE_IN | PAD_FUNC_ALT0 | PAD_LEVEL_LOW | PAD_PULL_UP  | PAD_STRENGTH_0)		/* Pin Use: PMIC_INT_L */

/*------------------------------------------------------------------------------
*	BUS Signal
*/
#define	PAD_BUS_STATIC_CNTL_SANTIAGO	(NX_CLKPWR_BUSPAD_STATIC_CNTL | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_ADDR_SANTIAGO	(NX_CLKPWR_BUSPAD_STATIC_ADDR | PAD_STRENGTH_2)
#define	PAD_BUS_STATIC_DATA_SANTIAGO	(NX_CLKPWR_BUSPAD_STATIC_DATA | PAD_STRENGTH_2)
#define	PAD_BUS_HSYNC_SANTIAGO	(NX_CLKPWR_BUSPAD_HSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_VSYNC_SANTIAGO	(NX_CLKPWR_BUSPAD_VSYNC | PAD_STRENGTH_2)
#define	PAD_BUS_DE_SANTIAGO	(NX_CLKPWR_BUSPAD_DE | PAD_STRENGTH_2)

extern const U32 io_pad_santiago[NUMBER_OF_GPIO_MODULE][32];

extern const U32 alv_pad_santiago[6];

extern const U32 bus_pad_santiago[6];
#endif /* __CFG_GPIO_SANTIAGO_H__ */
